// apps/preview-angular/src/angular/bubble-alignment.ts
import { Bubble, BubbleContent } from "@/angular-ui/bubble"
import { Component } from "@angular/core"

// apps/v4/examples/base/bubble-alignment.tsx
@Component({
  selector: "preview-bubble-alignment",
  standalone: true,
  imports: [Bubble, BubbleContent],
  template: `
    <div class="flex w-full max-w-sm flex-col gap-8 py-12">
      <div uiBubble variant="muted">
        <div uiBubbleContent>This bubble is aligned to the start. This is the default alignment.</div>
      </div>
      <div uiBubble align="end">
        <div uiBubbleContent>This bubble is aligned to the end. Use this for user messages.</div>
      </div>
    </div>
  `,
})
export class BubbleAlignmentComponent {}

export default BubbleAlignmentComponent

// apps/preview-vue/src/vue/bubble-alignment.vue
<script setup lang="ts">
import { Bubble, BubbleContent } from '@/ui/bubble'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Bubble variant="muted">
      <BubbleContent>
        This bubble is aligned to the start. This is the default alignment.
      </BubbleContent>
    </Bubble>
    <Bubble align="end">
      <BubbleContent>
        This bubble is aligned to the end. Use this for user messages.
      </BubbleContent>
    </Bubble>
  </div>
</template>
