// apps/preview-angular/src/angular/message-group.ts
import { Avatar, AvatarFallback, AvatarImage } from "@/angular-ui/avatar"
import { Bubble, BubbleContent } from "@/angular-ui/bubble"
import {
  Message,
  MessageAvatar,
  MessageContent,
  MessageGroup,
} from "@/angular-ui/message"
import { Component } from "@angular/core"

// apps/v4/examples/base/message-group.tsx
@Component({
  selector: "preview-message-group",
  standalone: true,
  imports: [Message, MessageAvatar, MessageContent, MessageGroup, Bubble, BubbleContent, Avatar, AvatarImage, AvatarFallback],
  template: `
    <div class="flex w-full max-w-sm flex-col gap-6 py-12">
      <div uiMessageGroup role="log" aria-live="polite">
        <div uiMessage>
          <div uiMessageAvatar></div>
          <div uiMessageContent>
            <div uiBubble variant="muted">
              <div uiBubbleContent>I checked the registry addresses.</div>
            </div>
          </div>
        </div>
        <div uiMessage>
          <div uiMessageAvatar>
            <span uiAvatar><img uiAvatarImage src="https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=96&h=96&fit=crop&q=80" alt="@rabbit" /><span uiAvatarFallback>CN</span></span>
          </div>
          <div uiMessageContent>
            <div uiBubble variant="muted">
              <div uiBubbleContent>
                The component and example JSON now live under the UI registry.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class MessageGroupDemoComponent {}

export default MessageGroupDemoComponent

// apps/preview-vue/src/vue/message-group.vue
<script setup lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from '@/ui/avatar'
import { Bubble, BubbleContent } from '@/ui/bubble'
import {
  Message,
  MessageAvatar,
  MessageContent,
  MessageGroup,
} from '@/ui/message'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-6 py-12">
    <MessageGroup>
      <Message>
        <MessageAvatar />
        <MessageContent>
          <Bubble variant="muted">
            <BubbleContent>I checked the registry addresses.</BubbleContent>
          </Bubble>
        </MessageContent>
      </Message>
      <Message>
        <MessageAvatar>
          <Avatar>
            <AvatarImage src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=96&auto=format&fit=crop" alt="@avatar" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
        </MessageAvatar>
        <MessageContent>
          <Bubble variant="muted">
            <BubbleContent>
              The component and example JSON now live under the UI registry.
            </BubbleContent>
          </Bubble>
        </MessageContent>
      </Message>
    </MessageGroup>
  </div>
</template>
