// apps/preview-svelte/src/svelte/message-scroller-streaming.svelte
<script lang="ts">
	import {
		MessageScrollerProvider,
		MessageScroller,
		MessageScrollerViewport,
		MessageScrollerContent,
		MessageScrollerItem,
		MessageScrollerButton,
	} from "@/svelte-ui/message-scroller/index.js";

	type Msg = { id: number; role: "user" | "assistant"; text: string; done?: boolean };

	const replies = [
		"Sure — here's the plan broken into steps.\n\n1. Keep the reader pinned while tokens stream in.\n2. Stop following the moment they scroll up.",
		"The key detail is edge detection: following only happens within a threshold of the bottom edge.",
		"That way history reading is never interrupted by live traffic.",
	];

	let messages = $state<Msg[]>([]);
	let nextId = $state(0);
	let streaming = $state(false);
	let timers: ReturnType<typeof setTimeout>[] = [];

	function startStream() {
		if (streaming) return;
		streaming = true;
		const id = nextId++;
		messages.push({ id, role: "assistant", text: "", done: false });

		const full = replies[nextId % replies.length];
		let i = 0;
		const tick = () => {
			const msg = messages.find((m) => m.id === id);
			if (!msg) return;
			msg.text = full.slice(0, ++i);
			if (i < full.length) {
				timers.push(setTimeout(tick, 18));
			} else {
				msg.done = true;
				streaming = false;
			}
		};
		timers.push(setTimeout(tick, 200));
	}
</script>

<MessageScrollerProvider>
	<div class="mx-auto flex w-full max-w-sm flex-col gap-4">
		<div class="rounded-xl border bg-card">
			<MessageScroller class="h-80">
				<MessageScrollerViewport>
					<MessageScrollerContent class="p-4 gap-2">
						{#each messages as message (message.id)}
							<MessageScrollerItem>
								<span
									class="inline-block max-w-[85%] rounded-lg px-3 py-2 text-sm whitespace-pre-wrap
										{message.role === 'user'
										? 'ml-auto bg-primary text-primary-foreground'
										: 'bg-muted'}"
								>
									{message.text}{message.done === false ? "▍" : ""}
								</span>
							</MessageScrollerItem>
						{/each}
					</MessageScrollerContent>
				</MessageScrollerViewport>
				<MessageScrollerButton />
			</MessageScroller>
		</div>
		<div class="flex gap-2">
			<button
				class="bg-primary text-primary-foreground h-9 flex-1 rounded-md text-sm font-medium disabled:opacity-50"
				disabled={streaming}
				onclick={() => {
					messages.push({
						id: nextId++,
						role: "user",
						text: "Walk me through it again.",
					});
					startStream();
				}}
			>
				{streaming ? "Streaming…" : "Send & stream reply"}
			</button>
		</div>
	</div>
</MessageScrollerProvider>

// apps/preview-vue/src/vue/message-scroller-streaming.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/ui/card"
import {
  MessageScroller,
  MessageScrollerButton,
  MessageScrollerContent,
  MessageScrollerItem,
  MessageScrollerProvider,
  MessageScrollerViewport,
} from "@/ui/message-scroller"
import RotateCwIcon from "@material-symbols/svg-400/rounded/refresh.svg?component"
import { onBeforeUnmount, ref } from "vue"

interface Msg {
  id: number
  role: "user" | "assistant"
  text: string
}

const scripted = [
  "Explain scroll anchoring like I am five.",
  "Imagine a comic strip taped to a wall. New panels appear at the bottom…",
  "…and the tape keeps the panel you are reading perfectly still.",
]
const tokens = scripted.flatMap((s) => s.split(" "))

const messages = ref<Msg[]>([{ id: 0, role: "user", text: scripted[0] }])
let nextId = 1
let cursor = scripted[1].split(" ").length + scripted[2].split(" ").length // skip echoed user msg words
let timer: ReturnType<typeof setInterval> | undefined

function startStream() {
  if (timer || cursor >= tokens.length) return
  messages.value.push({ id: nextId++, role: "assistant", text: "" })
  timer = setInterval(() => {
    const last = messages.value[messages.value.length - 1]
    last.text += `${tokens[cursor++]} `
    if (cursor >= tokens.length) {
      stop()
    }
  }, 120)
}

function stop() {
  if (timer) {
    clearInterval(timer)
    timer = undefined
  }
}

function reset() {
  stop()
  cursor = scripted[1].split(" ").length + scripted[2].split(" ").length
  messages.value = [{ id: 0, role: "user", text: scripted[0] }]
}

onBeforeUnmount(stop)
</script>

<template>
  <Card class="mx-auto flex h-[28rem] w-full max-w-sm flex-col gap-0">
    <CardHeader class="border-b">
      <CardTitle>Streaming Messages</CardTitle>
      <CardDescription
        >Auto-scroll follows the live edge of the conversation.</CardDescription
      >
      <CardAction>
        <Button
          variant="outline"
          size="icon"
          aria-label="Reset stream"
          @click="reset"
        >
          <RotateCwIcon />
        </Button>
      </CardAction>
    </CardHeader>
    <CardContent class="min-h-0 flex-1 overflow-hidden p-0">
      <MessageScrollerProvider auto-scroll>
        <MessageScroller class="h-full">
          <MessageScrollerViewport>
            <MessageScrollerContent class="gap-2 p-4">
              <MessageScrollerItem
                v-for="m in messages"
                :key="m.id"
                :scroll-anchor="true"
              >
                <span
                  class="inline-block max-w-[85%] rounded-lg px-3 py-2 text-sm whitespace-pre-wrap"
                  :class="
                    m.role === 'user'
                      ? 'ml-auto bg-primary text-primary-foreground'
                      : 'bg-muted'
                  "
                  >{{ m.text }}</span
                >
              </MessageScrollerItem>
            </MessageScrollerContent>
          </MessageScrollerViewport>
          <MessageScrollerButton />
        </MessageScroller>
      </MessageScrollerProvider>
    </CardContent>
    <div class="border-t p-4">
      <Button size="sm" :disabled="!!timer" @click="startStream">
        {{ timer ? "Streaming…" : "Simulate stream" }}
      </Button>
    </div>
  </Card>
</template>
