// apps/preview-angular/src/angular/switch-rtl.ts
import { Component } from "@angular/core"
import { Field, FieldContent, FieldDescription, FieldLabel } from "@/angular-ui/field"
import { Switch } from "@/angular-ui/switch"

@Component({
  selector: "preview-switch-rtl",
  standalone: true,
  imports: [Field, FieldContent, FieldLabel, FieldDescription, Switch],
  template: ` <div uiField orientation="horizontal" dir="rtl" class="max-w-sm">
    <div uiFieldContent>
      <label uiFieldLabel for="switch-focus-mode-rtl">
        المشاركة عبر الأجهزة
      </label>
      <p uiFieldDescription>
        يتم مشاركة التركيز عبر الأجهزة، ويتم إيقاف تشغيله عند مغادرة التطبيق.
      </p>
    </div>
    <button uiSwitch id="switch-focus-mode-rtl"></button>
  </div>`,
})
export class SwitchRtlComponent {}

export default SwitchRtlComponent

// apps/preview-vue/src/vue/switch-rtl.vue
<script setup lang="ts">
import { Field, FieldContent, FieldDescription, FieldLabel } from "@/ui/field"
import { Switch } from "@/ui/switch"
import { ref } from "vue"

const checked = ref(true)
</script>

<template>
  <Field orientation="horizontal" dir="rtl" class="max-w-sm">
    <FieldContent>
      <FieldLabel for="switch-focus-mode-rtl">المشاركة عبر الأجهزة</FieldLabel>
      <FieldDescription>
        تتم مشاركة التركيز عبر الأجهزة، ويتم إيقاف تشغيله عند مغادرة التطبيق.
      </FieldDescription>
    </FieldContent>
    <Switch id="switch-focus-mode-rtl" v-model="checked" dir="rtl" />
  </Field>
</template>
