// packages/registry-svelte/ui/bubble/bubble-reactions.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from "tailwind-variants";

	export const bubbleReactionsVariants = tv({
		base: "cn-bubble-reactions absolute z-10 flex w-fit items-center justify-center",
		variants: {
			side: {
				top: "cn-bubble-reactions-side-top",
				bottom: "cn-bubble-reactions-side-bottom",
			},
			align: {
				start: "cn-bubble-reactions-align-start",
				end: "cn-bubble-reactions-align-end",
			},
		},
		defaultVariants: {
			side: "bottom",
			align: "end",
		},
	});

	export type BubbleReactionsSide = VariantProps<
		typeof bubbleReactionsVariants
	>["side"];
	export type BubbleReactionsAlign = VariantProps<
		typeof bubbleReactionsVariants
	>["align"];
</script>

<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		side = "bottom",
		align = "end",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		side?: BubbleReactionsSide;
		align?: BubbleReactionsAlign;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="bubble-reactions"
	data-align={align}
	data-side={side}
	class={cn(bubbleReactionsVariants({ side, align }), className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/registry-vue/ui/bubble/BubbleReactions.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { BubbleReactionsSide, BubbleReactionsAlign } from "."
import { cn } from "@/lib/utils"
import { bubbleReactionsVariants } from "."

const props = withDefaults(
  defineProps<{
    side?: BubbleReactionsSide
    align?: BubbleReactionsAlign
    class?: HTMLAttributes["class"]
  }>(),
  {
    side: "bottom",
    align: "end",
  },
)
</script>

<template>
  <div
    data-slot="bubble-reactions"
    :data-align="props.align"
    :data-side="props.side"
    :class="
      cn(bubbleReactionsVariants({ side: props.side, align: props.align }), props.class)
    "
  >
    <slot />
  </div>
</template>
