// packages/registry-svelte/ui/bubble/bubble-group.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="bubble-group"
	class={cn("cn-bubble-group flex min-w-0 flex-col", className)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/registry-vue/ui/bubble/BubbleGroup.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="bubble-group"
    :class="cn('cn-bubble-group flex min-w-0 flex-col', props.class)"
  >
    <slot />
  </div>
</template>
