// packages/registry-svelte/blocks/sidebar-06/components/sidebar-opt-in-form.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-06 -->
<script lang="ts">
  import { Button } from "$lib/registry/ui/button/index.js"
  import * as Card from "$lib/registry/ui/card/index.js"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"
</script>

<Card.Root class="gap-2 py-4 shadow-none">
  <Card.Header class="px-4">
    <Card.Title class="text-sm">Subscribe to our newsletter</Card.Title>
    <Card.Description>
      Opt-in to receive updates and news about the sidebar.
    </Card.Description>
  </Card.Header>
  <Card.Content class="px-4">
    <form>
      <div class="grid gap-2.5">
        <Sidebar.Input type="email" placeholder="Email" />
        <Button
          class="w-full bg-sidebar-primary text-sidebar-primary-foreground shadow-none"
          size="sm"
        >
          Subscribe
        </Button>
      </div>
    </form>
  </Card.Content>
</Card.Root>

// packages/registry-vue/blocks/sidebar-06/SidebarOptInForm.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-06
import { Button } from '@/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/ui/card'
import { SidebarInput } from '@/ui/sidebar'
</script>

<template>
  <Card class="gap-2 py-4 shadow-none">
    <CardHeader class="px-4">
      <CardTitle class="text-sm">Subscribe to our newsletter</CardTitle>
      <CardDescription>
        Opt-in to receive updates and news about the sidebar.
      </CardDescription>
    </CardHeader>
    <CardContent class="px-4">
      <form>
        <div class="grid gap-2.5">
          <SidebarInput type="email" placeholder="Email" />
          <Button
            class="w-full bg-sidebar-primary text-sidebar-primary-foreground shadow-none"
            size="sm"
          >
            Subscribe
          </Button>
        </div>
      </form>
    </CardContent>
  </Card>
</template>
