// packages/registry-svelte/ui/attachment/attachment-action.svelte
<script lang="ts">
	import type { ComponentProps } from "svelte";
	import { cn } from "$lib/utils.js";
	import { Button } from "$lib/registry/ui/button/index.js";

	let {
		class: className,
		variant = "ghost",
		size = "icon-xs",
		children,
		...restProps
	}: Omit<ComponentProps<typeof Button>, "size"> & {
		size?: ComponentProps<typeof Button>["size"];
	} = $props();
</script>

<Button
	data-slot="attachment-action"
	{variant}
	{size}
	class={cn("cn-attachment-action", className)}
	{...restProps}
>
	{@render children?.()}
</Button>

// packages/registry-vue/ui/attachment/AttachmentAction.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { ButtonVariants } from "@/ui/button"
import { cn } from "@/lib/utils"
import { buttonVariants } from "@/ui/button"

const props = withDefaults(
  defineProps<{
    variant?: ButtonVariants["variant"]
    size?: ButtonVariants["size"]
    class?: HTMLAttributes["class"]
  }>(),
  {
    variant: "ghost",
    size: "icon-xs",
  },
)
</script>

<template>
  <button
    data-slot="attachment-action"
    :class="
      cn(
        buttonVariants({ variant: props.variant, size: props.size }),
        'cn-attachment-action',
        props.class,
      )
    "
    type="button"
  >
    <slot />
  </button>
</template>
