// packages/registry-svelte/blocks/sidebar-13/components/settings-dialog.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-13 -->
<script lang="ts">
  import CreditCard from "~icons/ms/credit_card"
  import UsersIcon from "~icons/ms/group"
  import Bell from "~icons/ms/notifications"
  import User from "~icons/ms/person"
  import * as Breadcrumb from "$lib/registry/ui/breadcrumb/index.js"
  import { Button } from "$lib/registry/ui/button/index.js"
  import * as Dialog from "$lib/registry/ui/dialog/index.js"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  let open = $state(false)

  const navItems = [
    { name: "Notifications", icon: Bell },
    { name: "Billing", icon: CreditCard },
    { name: "Profile", icon: User },
    { name: "Team", icon: UsersIcon },
  ]
</script>

<Dialog.Root bind:open>
  <Dialog.Trigger>
    {#snippet child({ props })}
      <Button size="sm" {...props}>Open Dialog</Button>
    {/snippet}
  </Dialog.Trigger>
  <Dialog.Content
    class="overflow-hidden p-0 md:max-h-[500px] md:max-w-[700px] lg:max-w-[800px]"
  >
    <Dialog.Title class="sr-only">Settings</Dialog.Title>
    <Dialog.Description class="sr-only"
      >Customize your settings here.</Dialog.Description
    >
    <Sidebar.Provider class="items-start">
      <Sidebar.Root collapsible="none" class="hidden md:flex">
        <Sidebar.Content>
          <Sidebar.Group>
            <Sidebar.GroupContent>
              <Sidebar.Menu>
                {#each navItems as item (item.name)}
                  <Sidebar.MenuItem>
                    <Sidebar.MenuButton>
                      {#snippet child({ props })}
                        <a href="#" {...props}>
                          <item.icon />
                          <span>{item.name}</span>
                        </a>
                      {/snippet}
                    </Sidebar.MenuButton>
                  </Sidebar.MenuItem>
                {/each}
              </Sidebar.Menu>
            </Sidebar.GroupContent>
          </Sidebar.Group>
        </Sidebar.Content>
      </Sidebar.Root>
      <main class="flex h-[480px] flex-1 flex-col overflow-hidden">
        <header
          class="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12"
        >
          <div class="flex items-center gap-2 px-4">
            <Breadcrumb.Root>
              <Breadcrumb.List>
                <Breadcrumb.Item class="hidden md:block">
                  <Breadcrumb.Link href="#Settings">Settings</Breadcrumb.Link>
                </Breadcrumb.Item>
                <Breadcrumb.Separator class="hidden md:block" />
                <Breadcrumb.Item>
                  <Breadcrumb.Page>Messages & media</Breadcrumb.Page>
                </Breadcrumb.Item>
              </Breadcrumb.List>
            </Breadcrumb.Root>
          </div>
        </header>
        <div class="flex flex-1 flex-col gap-4 overflow-y-auto p-4 pt-0">
          {#each Array(5) as _, i (i)}
            <div class="aspect-video max-w-3xl rounded-xl bg-muted/50"></div>
          {/each}
        </div>
      </main>
    </Sidebar.Provider>
  </Dialog.Content>
</Dialog.Root>

// packages/registry-vue/blocks/sidebar-13/SettingsDialog.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-13
import { ref } from 'vue'
import type { Component } from 'vue'
import Notifications from '@material-symbols/svg-400/rounded/notifications.svg?component'
import Menu from '@material-symbols/svg-400/rounded/menu.svg?component'
import Home from '@material-symbols/svg-400/rounded/home.svg?component'
import Paintbrush from '@material-symbols/svg-400/rounded/format_paint.svg?component'
import Chat from '@material-symbols/svg-400/rounded/chat.svg?component'
import Globe from '@material-symbols/svg-400/rounded/globe.svg?component'
import Keyboard from '@material-symbols/svg-400/rounded/keyboard.svg?component'
import Check from '@material-symbols/svg-400/rounded/check.svg?component'
import Video from '@material-symbols/svg-400/rounded/videocam.svg?component'
import LinkIcon from '@material-symbols/svg-400/rounded/link.svg?component'
import Lock from '@material-symbols/svg-400/rounded/lock.svg?component'
import Settings from '@material-symbols/svg-400/rounded/settings.svg?component'
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/ui/breadcrumb'
import { Button } from '@/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
  DialogTrigger,
} from '@/ui/dialog'
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarProvider,
} from '@/ui/sidebar'

const data = {
  nav: [
    { name: 'Notifications', icon: Notifications as Component },
    { name: 'Navigation', icon: Menu as Component },
    { name: 'Home', icon: Home as Component },
    { name: 'Appearance', icon: Paintbrush as Component },
    { name: 'Messages & media', icon: Chat as Component },
    { name: 'Language & region', icon: Globe as Component },
    { name: 'Accessibility', icon: Keyboard as Component },
    { name: 'Mark as read', icon: Check as Component },
    { name: 'Audio & video', icon: Video as Component },
    { name: 'Connected accounts', icon: LinkIcon as Component },
    { name: 'Privacy & visibility', icon: Lock as Component },
    { name: 'Advanced', icon: Settings as Component },
  ],
}

const open = ref(true)
const placeholderRows = Array.from({ length: 10 })
</script>

<template>
  <Dialog v-model:open="open">
    <DialogTrigger as-child>
      <Button size="sm">Open Dialog</Button>
    </DialogTrigger>
    <DialogContent class="overflow-hidden p-0 md:max-h-[500px] md:max-w-[700px] lg:max-w-[800px]">
      <DialogTitle class="sr-only">Settings</DialogTitle>
      <DialogDescription class="sr-only">
        Customize your settings here.
      </DialogDescription>
      <SidebarProvider class="items-start">
        <Sidebar collapsible="none" class="hidden md:flex">
          <SidebarContent>
            <SidebarGroup>
              <SidebarGroupContent>
                <SidebarMenu>
                  <SidebarMenuItem v-for="item in data.nav" :key="item.name">
                    <SidebarMenuButton as-child :is-active="item.name === 'Messages & media'">
                      <a href="#">
                        <component :is="item.icon" />
                        <span>{{ item.name }}</span>
                      </a>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                </SidebarMenu>
              </SidebarGroupContent>
            </SidebarGroup>
          </SidebarContent>
        </Sidebar>
        <main class="flex h-[480px] flex-1 flex-col overflow-hidden">
          <header class="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
            <div class="flex items-center gap-2 px-4">
              <Breadcrumb>
                <BreadcrumbList>
                  <BreadcrumbItem class="hidden md:block">
                    <BreadcrumbLink href="#">Settings</BreadcrumbLink>
                  </BreadcrumbItem>
                  <BreadcrumbSeparator class="hidden md:block" />
                  <BreadcrumbItem>
                    <BreadcrumbPage>Messages & media</BreadcrumbPage>
                  </BreadcrumbItem>
                </BreadcrumbList>
              </Breadcrumb>
            </div>
          </header>
          <div class="flex flex-1 flex-col gap-4 overflow-y-auto p-4 pt-0">
            <div
              v-for="(row, i) in placeholderRows"
              :key="i"
              class="aspect-video max-w-3xl rounded-xl bg-muted/50"
            />
          </div>
        </main>
      </SidebarProvider>
    </DialogContent>
  </Dialog>
</template>
