// apps/v4/registry/new-york-v4/ui/item.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"
import { Separator } from "@/registry/new-york-v4/ui/separator"

function ItemGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      role="list"
      data-slot="item-group"
      className={cn("group/item-group flex flex-col", className)}
      {...props}
    />
  )
}

function ItemSeparator({
  className,
  ...props
}: React.ComponentProps<typeof Separator>) {
  return (
    <Separator
      data-slot="item-separator"
      orientation="horizontal"
      className={cn("my-0", className)}
      {...props}
    />
  )
}

const itemVariants = cva(
  "group/item flex flex-wrap items-center rounded-md border border-transparent text-sm transition-colors duration-100 outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 [a]:transition-colors [a]:hover:bg-accent/50",
  {
    variants: {
      variant: {
        default: "bg-transparent",
        outline: "border-border",
        muted: "bg-muted/50",
      },
      size: {
        default: "gap-4 p-4",
        sm: "gap-2.5 px-4 py-3",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Item({
  className,
  variant = "default",
  size = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"div"> &
  VariantProps<typeof itemVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot.Root : "div"
  return (
    <Comp
      data-slot="item"
      data-variant={variant}
      data-size={size}
      className={cn(itemVariants({ variant, size, className }))}
      {...props}
    />
  )
}

const itemMediaVariants = cva(
  "flex shrink-0 items-center justify-center gap-2 group-has-[[data-slot=item-description]]/item:translate-y-0.5 group-has-[[data-slot=item-description]]/item:self-start [&_svg]:pointer-events-none",
  {
    variants: {
      variant: {
        default: "bg-transparent",
        icon: "size-8 rounded-sm border bg-muted [&_svg:not([class*=size-])]:size-4",
        image:
          "size-10 overflow-hidden rounded-sm [&_img]:size-full [&_img]:object-cover",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function ItemMedia({
  className,
  variant = "default",
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof itemMediaVariants>) {
  return (
    <div
      data-slot="item-media"
      data-variant={variant}
      className={cn(itemMediaVariants({ variant, className }))}
      {...props}
    />
  )
}

function ItemContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-content"
      className={cn(
        "flex flex-1 flex-col gap-1 [&+[data-slot=item-content]]:flex-none",
        className
      )}
      {...props}
    />
  )
}

function ItemTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-title"
      className={cn(
        "flex w-fit items-center gap-2 text-sm leading-snug font-medium",
        className
      )}
      {...props}
    />
  )
}

function ItemDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="item-description"
      className={cn(
        "line-clamp-2 text-sm leading-normal font-normal text-balance text-muted-foreground",
        "[&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",
        className
      )}
      {...props}
    />
  )
}

function ItemActions({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-actions"
      className={cn("flex items-center gap-2", className)}
      {...props}
    />
  )
}

function ItemHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-header"
      className={cn(
        "flex basis-full items-center justify-between gap-2",
        className
      )}
      {...props}
    />
  )
}

function ItemFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="item-footer"
      className={cn(
        "flex basis-full items-center justify-between gap-2",
        className
      )}
      {...props}
    />
  )
}

export {
  Item,
  ItemMedia,
  ItemContent,
  ItemActions,
  ItemGroup,
  ItemSeparator,
  ItemTitle,
  ItemDescription,
  ItemHeader,
  ItemFooter,
}

// packages/registry-angular/ui/item/item.component.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  input
} from "@angular/core"

import { cn } from "@/lib/utils"
import {
  itemMediaVariants,
  itemVariants,
  type ItemMediaVariant,
  type ItemSize,
  type ItemVariant
} from "./item.variants"

/**
 * Angular port of @force-ui/item (force-ui style).
 *
 * Attribute selectors — each part decorates whatever host element the caller
 * writes, preserving native semantics (Angular's idiomatic equivalent of
 * React's asChild). Host an Item on `<a>` to get a clickable row; the
 * `[a]:hover:bg-muted` / focus-ring classes in cn-item activate there.
 *
 * Usage:
 *   <div uiItemGroup>
 *     <a href="#" uiItem variant="outline" role="listitem">
 *       <div uiItemMedia variant="icon"><svg …/></div>
 *       <div uiItemContent>
 *         <div uiItemTitle>Title</div>
 *         <p uiItemDescription>Description</p>
 *       </div>
 *       <div uiItemActions>…</div>
 *     </a>
 *   </div>
 *
 * ItemGroup carries `role="list"` (registry-verbatim); give each purely
 * informational row `role="listitem"` or an axe aria-required-children
 * violation follows.
 *
 * ItemSeparator reproduces ui/separator's host classes inline — Angular
 * attribute selectors cannot nest one component inside another (same pattern
 * as p4one's SEPARATOR_BASE_CLASS reuse).
 */
@Component({
  selector: "[uiItemGroup]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: "list",
    "data-slot": "item-group",
    "[class]": "classes()"
  }
})
export class ItemGroupComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-group group/item-group flex w-full flex-col", this.className())
  )
}

@Component({
  selector: "[uiItemSeparator]",
  standalone: true,
  templateUrl: "./item-separator.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-separator",
    "[attr.role]": "decorative() ? 'none' : 'separator'",
    "[attr.aria-orientation]":
      "!decorative() && orientation() === 'vertical' ? 'vertical' : null",
    "[attr.data-orientation]": "orientation()",
    "[class]": "classes()"
  }
})
export class ItemSeparatorComponent {
  readonly orientation = input<"horizontal" | "vertical">("horizontal")
  readonly decorative = input(true, { transform: booleanAttribute })
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      // SeparatorComponent's host classes (see DIVERGENCES.md §separator-1 —
      // data-[orientation] variants directly, cn-separator* tokens unused).
      "shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-px data-[orientation=vertical]:self-stretch",
      "cn-item-separator",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItem]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item",
    "[attr.data-variant]": "variant()",
    "[attr.data-size]": "size()",
    "[class]": "classes()"
  }
})
export class ItemComponent {
  readonly variant = input<ItemVariant>("default")
  readonly size = input<ItemSize>("default")
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(itemVariants({ variant: this.variant(), size: this.size() }), this.className())
  )
}

@Component({
  selector: "[uiItemMedia]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-media",
    "[attr.data-variant]": "variant()",
    "[class]": "classes()"
  }
})
export class ItemMediaComponent {
  readonly variant = input<ItemMediaVariant>("default")
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(itemMediaVariants({ variant: this.variant() }), this.className())
  )
}

@Component({
  selector: "[uiItemContent]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-content",
    "[class]": "classes()"
  }
})
export class ItemContentComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "cn-item-content flex flex-1 flex-col [&+[data-slot=item-content]]:flex-none",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItemTitle]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-title",
    "[class]": "classes()"
  }
})
export class ItemTitleComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-title line-clamp-1 flex w-fit items-center", this.className())
  )
}

@Component({
  selector: "[uiItemDescription]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-description",
    "[class]": "classes()"
  }
})
export class ItemDescriptionComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn(
      "cn-item-description line-clamp-2 font-normal [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary",
      this.className()
    )
  )
}

@Component({
  selector: "[uiItemActions]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-actions",
    "[class]": "classes()"
  }
})
export class ItemActionsComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-actions flex items-center", this.className())
  )
}

@Component({
  selector: "[uiItemHeader]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-header",
    "[class]": "classes()"
  }
})
export class ItemHeaderComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-header flex basis-full items-center justify-between", this.className())
  )
}

@Component({
  selector: "[uiItemFooter]",
  standalone: true,
  templateUrl: "./item.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-slot": "item-footer",
    "[class]": "classes()"
  }
})
export class ItemFooterComponent {
  readonly className = input<string | undefined>(undefined, { alias: "class" })

  protected readonly classes = computed(() =>
    cn("cn-item-footer flex basis-full items-center justify-between", this.className())
  )
}
