// packages/registry-svelte/blocks/sidebar-15/components/sidebar-right.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-15 -->
<script lang="ts">
  import Plus from "~icons/ms/add"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  import Calendars from "./calendars.svelte"
  import DatePicker from "./date-picker.svelte"
  import NavUser from "./nav-user.svelte"

  const user = {
    name: "shadcn",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  }
</script>

<Sidebar.Root
  collapsible="none"
  class="sticky top-0 hidden h-svh border-l lg:flex"
>
  <Sidebar.Header class="h-16 border-b border-sidebar-border">
    <NavUser {user} />
  </Sidebar.Header>
  <Sidebar.Content>
    <DatePicker />
    <Sidebar.Separator class="mx-0" />
    <Calendars
      calendars={[{ name: "Design Systems", items: ["Personal", "Work"] }]}
    />
  </Sidebar.Content>
  <Sidebar.Footer>
    <Sidebar.Menu>
      <Sidebar.MenuItem>
        <Sidebar.MenuButton>
          <Plus />
          <span>New Calendar</span>
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  </Sidebar.Footer>
</Sidebar.Root>

// packages/registry-vue/blocks/sidebar-15/SidebarRight.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-15
import Add from '@material-symbols/svg-400/rounded/add.svg?component'
import NavUser from './NavUser.vue'
import DatePicker from './DatePicker.vue'
import Calendars from './Calendars.vue'
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarSeparator,
} from '@/ui/sidebar'

// This is sample data.
const data = {
  user: {
    name: 'shadcn',
    email: 'm@example.com',
    avatar: '/avatars/shadcn.jpg',
  },
  calendars: [
    { name: 'My Calendars', items: ['Personal', 'Work', 'Family'] },
    { name: 'Favorites', items: ['Holidays', 'Birthdays'] },
    { name: 'Other', items: ['Travel', 'Reminders', 'Deadlines'] },
  ],
}
</script>

<template>
  <Sidebar collapsible="none" class="sticky top-0 hidden h-svh border-l lg:flex">
    <SidebarHeader class="h-16 border-b border-sidebar-border">
      <NavUser :user="data.user" />
    </SidebarHeader>
    <SidebarContent>
      <DatePicker />
      <SidebarSeparator class="mx-0" />
      <Calendars :calendars="data.calendars" />
    </SidebarContent>
    <SidebarFooter>
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton>
            <Add />
            <span>New Calendar</span>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarFooter>
  </Sidebar>
</template>
