// packages/registry-svelte/ui/message/message-header.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="message-header"
	class={cn(
		"cn-message-header flex max-w-full min-w-0 items-center",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/registry-vue/ui/message/MessageHeader.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="message-header"
    :class="
      cn('cn-message-header flex max-w-full min-w-0 items-center', props.class)
    "
  >
    <slot />
  </div>
</template>
