// packages/registry-svelte/blocks/sidebar-16/components/app-sidebar.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-16 -->
<script lang="ts">
  import FolderIcon from "~icons/ms/folder"
  import AudioLines from "~icons/ms/graphic_eq"
  import Command from "~icons/ms/keyboard_command_key"
  import Map from "~icons/ms/map"
  import PieChartIcon from "~icons/ms/pie_chart"
  import Send from "~icons/ms/send"
  import LifeBuoy from "~icons/ms/support"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  import NavMain from "./nav-main.svelte"
  import NavProjects from "./nav-projects.svelte"
  import NavSecondary from "./nav-secondary.svelte"
  import NavUser from "./nav-user.svelte"

  const data = {
    user: {
      name: "shadcn",
      email: "m@example.com",
      avatar: "/avatars/shadcn.jpg",
    },
    navMain: [
      { title: "Dashboard", url: "#", icon: PieChartIcon, isActive: true },
      { title: "Lifecycle", url: "#", icon: Map },
      {
        title: "Analytics",
        url: "#",
        icon: AudioLines,
        items: [{ title: "Usage", url: "#" }],
      },
    ],
    navSecondary: [
      { title: "Support", url: "#", icon: LifeBuoy },
      { title: "Feedback", url: "#", icon: Send },
    ],
    projects: [
      { name: "Design Engineering", url: "#", icon: PieChartIcon },
      { name: "Sales & Marketing", url: "#", icon: Map },
      { name: "Travel", url: "#", icon: LifeBuoy },
      { name: "Support", url: "#", icon: Send },
    ],
  }
</script>

<Sidebar.Root
  class="top-(--header-height) h-[calc(100svh-var(--header-height))]!"
>
  <Sidebar.Header>
    <Sidebar.Menu>
      <Sidebar.MenuItem>
        <Sidebar.MenuButton size="lg">
          {#snippet child({ props })}
            <a href="#" {...props}>
              <div
                class="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground"
              >
                <Command class="size-4" />
              </div>
              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-medium">Acme Inc</span>
                <span class="truncate text-xs">Enterprise</span>
              </div>
            </a>
          {/snippet}
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  </Sidebar.Header>
  <Sidebar.Content>
    <NavMain items={data.navMain} />
    <NavProjects projects={data.projects} />
    <NavSecondary items={data.navSecondary} class="mt-auto" />
  </Sidebar.Content>
  <Sidebar.Footer>
    <NavUser user={data.user} />
  </Sidebar.Footer>
</Sidebar.Root>

// packages/registry-vue/blocks/sidebar-16/AppSidebar.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-16
import { h } from 'vue'
import type { Component } from 'vue'
import NavMain from './NavMain.vue'
import NavProjects from './NavProjects.vue'
import NavSecondary from './NavSecondary.vue'
import NavUser from './NavUser.vue'
import Terminal from '@material-symbols/svg-400/rounded/terminal.svg?component'
import SmartToy from '@material-symbols/svg-400/rounded/smart_toy.svg?component'
import MenuBook from '@material-symbols/svg-400/rounded/menu_book.svg?component'
import Tune from '@material-symbols/svg-400/rounded/tune.svg?component'
import ContactSupport from '@material-symbols/svg-400/rounded/contact_support.svg?component'
import Send from '@material-symbols/svg-400/rounded/send.svg?component'
import DesignServices from '@material-symbols/svg-400/rounded/design_services.svg?component'
import PieChart from '@material-symbols/svg-400/rounded/pie_chart.svg?component'
import Map from '@material-symbols/svg-400/rounded/map.svg?component'
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from '@/ui/sidebar'

// Lucide command icon as a functional component.
const Command = () =>
  h('svg', { xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': '2', 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
    h('path', { d: 'M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3' }),
  ])

// This is sample data.
const data = {
  user: {
    name: 'shadcn',
    email: 'm@example.com',
    avatar: '/avatars/shadcn.jpg',
  },
  navMain: [
    {
      title: 'Playground',
      url: '#',
      icon: Terminal as Component,
      isActive: true,
      items: [
        { title: 'History', url: '#' },
        { title: 'Starred', url: '#' },
        { title: 'Settings', url: '#' },
      ],
    },
    {
      title: 'Models',
      url: '#',
      icon: SmartToy as Component,
      items: [
        { title: 'Genesis', url: '#' },
        { title: 'Explorer', url: '#' },
        { title: 'Quantum', url: '#' },
      ],
    },
    {
      title: 'Documentation',
      url: '#',
      icon: MenuBook as Component,
      items: [
        { title: 'Introduction', url: '#' },
        { title: 'Get Started', url: '#' },
        { title: 'Tutorials', url: '#' },
        { title: 'Changelog', url: '#' },
      ],
    },
    {
      title: 'Settings',
      url: '#',
      icon: Tune as Component,
      items: [
        { title: 'General', url: '#' },
        { title: 'Team', url: '#' },
        { title: 'Billing', url: '#' },
        { title: 'Limits', url: '#' },
      ],
    },
  ],
  navSecondary: [
    { title: 'Support', url: '#', icon: ContactSupport as Component },
    { title: 'Feedback', url: '#', icon: Send as Component },
  ],
  projects: [
    { name: 'Design Engineering', url: '#', icon: DesignServices },
    { name: 'Sales & Marketing', url: '#', icon: PieChart },
    { name: 'Travel', url: '#', icon: Map },
  ],
}
</script>

<template>
  <Sidebar class="top-(--header-height) h-[calc(100svh-var(--header-height))]!">
    <SidebarHeader>
      <SidebarMenu>
        <SidebarMenuItem>
          <SidebarMenuButton size="lg" as-child>
            <a href="#">
              <div class="flex aspect-square size-8 items-center justify-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground">
                <Command class="size-4" />
              </div>
              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-medium">Acme Inc</span>
                <span class="truncate text-xs">Enterprise</span>
              </div>
            </a>
          </SidebarMenuButton>
        </SidebarMenuItem>
      </SidebarMenu>
    </SidebarHeader>
    <SidebarContent>
      <NavMain :items="data.navMain" />
      <NavProjects :projects="data.projects" />
      <NavSecondary :items="data.navSecondary" class="mt-auto" />
    </SidebarContent>
    <SidebarFooter>
      <NavUser :user="data.user" />
    </SidebarFooter>
  </Sidebar>
</template>
