// packages/registry-svelte/blocks/sidebar-08/components/nav-main.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-08 -->
<script lang="ts">
  import ChevronRight from "~icons/ms/chevron_right"
  import Folder from "~icons/ms/folder"
  import * as Collapsible from "$lib/registry/ui/collapsible/index.js"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  let {
    items,
  }: {
    items: {
      title: string
      url: string
      icon: typeof Folder
      isActive?: boolean
      items?: { title: string; url: string }[]
    }[]
  } = $props()

  let openState = $state(
    Object.fromEntries(items.map((i) => [i.title, i.isActive ?? false]))
  )
</script>

<Sidebar.Group>
  <Sidebar.GroupLabel>Platform</Sidebar.GroupLabel>
  <Sidebar.Menu>
    {#each items as item (item.title)}
      <Collapsible.Root bind:open={openState[item.title]}>
        <Sidebar.MenuItem>
          <Sidebar.MenuButton tooltipContent={item.title}>
            {#snippet child({ props })}
              <a href={item.url} {...props}>
                <item.icon />
                <span>{item.title}</span>
              </a>
            {/snippet}
          </Sidebar.MenuButton>
          {#if item.items?.length}
            <Collapsible.Trigger>
              {#snippet child({ props })}
                <Sidebar.MenuAction
                  class="data-[state=open]:rotate-90"
                  {...props}
                >
                  <ChevronRight />
                  <span class="sr-only">Toggle</span>
                </Sidebar.MenuAction>
              {/snippet}
            </Collapsible.Trigger>
            <Collapsible.Content>
              <Sidebar.MenuSub>
                {#each item.items as subItem (subItem.title)}
                  <Sidebar.MenuSubItem>
                    <Sidebar.MenuSubButton>
                      {#snippet child({ props })}
                        <a href={subItem.url} {...props}
                          ><span>{subItem.title}</span></a
                        >
                      {/snippet}
                    </Sidebar.MenuSubButton>
                  </Sidebar.MenuSubItem>
                {/each}
              </Sidebar.MenuSub>
            </Collapsible.Content>
          {/if}
        </Sidebar.MenuItem>
      </Collapsible.Root>
    {/each}
  </Sidebar.Menu>
</Sidebar.Group>

// packages/registry-vue/blocks/sidebar-16/NavMain.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-16
import ChevronRight from '@material-symbols/svg-400/rounded/chevron_right.svg?component'
import Terminal from '@material-symbols/svg-400/rounded/terminal.svg?component'
import SmartToy from '@material-symbols/svg-400/rounded/smart_toy.svg?component'
import MenuBook from '@material-symbols/svg-400/rounded/menu_book.svg?component'
import Tune from '@material-symbols/svg-400/rounded/tune.svg?component'
import type { Component } from 'vue'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/ui/collapsible'
import {
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
} from '@/ui/sidebar'

const props = defineProps<{
  items: {
    title: string
    url: string
    icon: Component
    isActive?: boolean
    items?: {
      title: string
      url: string
    }[]
  }[]
}>()
</script>

<template>
  <SidebarGroup>
    <SidebarGroupLabel>Platform</SidebarGroupLabel>
    <SidebarMenu>
      <Collapsible
        v-for="item in props.items"
        :key="item.title"
        as-child
        :default-open="item.isActive"
      >
        <SidebarMenuItem>
          <SidebarMenuButton as-child :tooltip="item.title">
            <a :href="item.url">
              <component :is="item.icon" />
              <span>{{ item.title }}</span>
            </a>
          </SidebarMenuButton>
          <template v-if="item.items?.length">
            <CollapsibleTrigger as-child>
              <SidebarMenuAction class="data-[state=open]:rotate-90">
                <ChevronRight />
                <span class="sr-only">Toggle</span>
              </SidebarMenuAction>
            </CollapsibleTrigger>
            <CollapsibleContent>
              <SidebarMenuSub>
                <SidebarMenuSubItem v-for="subItem in item.items" :key="subItem.title">
                  <SidebarMenuSubButton as-child>
                    <a :href="subItem.url">
                      <span>{{ subItem.title }}</span>
                    </a>
                  </SidebarMenuSubButton>
                </SidebarMenuSubItem>
              </SidebarMenuSub>
            </CollapsibleContent>
          </template>
        </SidebarMenuItem>
      </Collapsible>
    </SidebarMenu>
  </SidebarGroup>
</template>
