// packages/registry-vue/ui/attachment/AttachmentActions.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="attachment-actions"
    :class="cn('cn-attachment-actions flex shrink-0 items-center', props.class)"
  >
    <slot />
  </div>
</template>

// packages/registry-svelte/ui/attachment/attachment-actions.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="attachment-actions"
	class={cn("cn-attachment-actions flex shrink-0 items-center", className)}
	{...restProps}
>
	{@render children?.()}
</div>
