// packages/registry-vue/ui/attachment/AttachmentTrigger.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = withDefaults(
  defineProps<{
    /** [FORCE-UI] element to render, e.g. `"a"` for link triggers (defaults to `"button"`) */
    as?: string
    class?: HTMLAttributes["class"]
  }>(),
  {
    as: "button",
  },
)
</script>

<template>
  <component
    :is="props.as"
    data-slot="attachment-trigger"
    :type="props.as === 'button' ? 'button' : undefined"
    :class="
      cn('cn-attachment-trigger absolute inset-0 z-10 outline-none', props.class)
    "
  >
    <slot />
  </component>
</template>

// packages/registry-svelte/ui/attachment/attachment-trigger.svelte
<script lang="ts">
	import type { HTMLButtonAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		type = "button",
		children,
		...restProps
	}: WithElementRef<HTMLButtonAttributes> = $props();
</script>

<!-- [FORCE-UI] absolute overlay trigger covering the whole attachment; React
     version supports a `render` prop for custom elements — pass an anchor via
     the default slot composition instead when a link target is needed. -->
<button
	bind:this={ref}
	data-slot="attachment-trigger"
	{type}
	class={cn("cn-attachment-trigger absolute inset-0 z-10 outline-none", className)}
	{...restProps}
>
	{@render children?.()}
</button>
