// packages/registry-vue/ui/attachment/AttachmentContent.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="attachment-content"
    :class="cn('cn-attachment-content max-w-full min-w-0 flex-1', props.class)"
  >
    <slot />
  </div>
</template>

// packages/registry-svelte/ui/attachment/attachment-content.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="attachment-content"
	class={cn("cn-attachment-content max-w-full min-w-0 flex-1", className)}
	{...restProps}
>
	{@render children?.()}
</div>
