// apps/preview-svelte/src/svelte/date-picker-basic.svelte
<script lang="ts">
	import CalendarIcon from "~icons/ms/calendar_month";
	import { DateFormatter, type DateValue, getLocalTimeZone } from "@internationalized/date";
	import { cn } from "@/svelte-lib/utils.js";
	import { buttonVariants } from "@/svelte-ui/button/index.js";
	import { Calendar } from "@/svelte-ui/calendar/index.js";
	import * as Popover from "@/svelte-ui/popover/index.js";

	const df = new DateFormatter("en-US", {
		dateStyle: "long",
	});

	let value = $state<DateValue | undefined>();
</script>

<Popover.Root>
	<Popover.Trigger
		class={cn(
			buttonVariants({
				variant: "outline",
				class: "w-[280px] justify-start text-start font-normal",
			}),
			!value && "text-muted-foreground"
		)}
	>
		<CalendarIcon class="me-2 size-4" />
		{value ? df.format(value.toDate(getLocalTimeZone())) : "Pick a date"}
	</Popover.Trigger>
	<Popover.Content class="w-auto p-0" align="start">
		<Calendar type="single" bind:value />
	</Popover.Content>
</Popover.Root>

// packages/registry-vue/examples/date-picker/DatePickerBasic.vue
<script setup lang="ts">
import { ref } from 'vue'
import type { Ref } from 'vue'
import type { DateValue } from '@internationalized/date'
import { getLocalTimeZone, today } from '@internationalized/date'
import CalendarIcon from "@material-symbols/svg-400/rounded/calendar_month.svg?component"
import { Button } from '@/ui/button'
import { Calendar } from '@/ui/calendar'
import { Field, FieldLabel } from '@/ui/field'
import { Popover, PopoverContent, PopoverTrigger } from '@/ui/popover'

const date = ref<DateValue>() as Ref<DateValue | undefined>
const open = ref(false)

function display(value?: DateValue) {
  return value ? value.toDate(getLocalTimeZone()).toLocaleDateString('en-US', { dateStyle: 'long' }) : ''
}
</script>

<template>
  <Field class="mx-auto w-56">
    <FieldLabel for="date-picker-basic">Date</FieldLabel>
    <Popover v-model:open="open">
      <PopoverTrigger as-child>
        <Button
          id="date-picker-basic"
          variant="outline"
          class="justify-start font-normal"
        >
          <CalendarIcon data-icon="inline-start" />
          {{ date ? display(date) : 'Pick a date' }}
        </Button>
      </PopoverTrigger>
      <PopoverContent class="w-auto p-0" align="start">
        <Calendar
          :model-value="date"
          @update:model-value="(value) => {
            if (value) {
              date = value
              open = false
            }
          }"
        />
      </PopoverContent>
    </Popover>
  </Field>
</template>
