// apps/v4/styles/radix-force-ui/ui-rtl/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"

const badgeVariants = cva(
  "group/badge inline-flex h-6 w-fit shrink-0 items-center justify-center gap-1 overflow-hidden rounded-full border border-transparent px-2.5 py-0.5 text-xs font-medium tracking-wide whitespace-nowrap uppercase transition-colors focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 has-data-[icon=inline-end]:pe-1.5 has-data-[icon=inline-start]:ps-1.5 aria-invalid:border-destructive aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 [&>svg]:pointer-events-none [&>svg]:size-3.5!",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground",
        secondary: "bg-secondary text-secondary-foreground",
        destructive: "bg-error-subtle text-error",
        warning: "bg-warning-subtle text-warning",
        success: "bg-success-subtle text-success", // [FORCE-UI]
        info: "bg-info-subtle text-info", // [FORCE-UI]
        "success-solid": "bg-success-solid text-on-success", // [FORCE-UI]
        "warning-solid":
          "bg-warning-solid text-on-warning dark:text-on-warning", // [FORCE-UI]
        "info-solid": "bg-info-solid text-on-info", // [FORCE-UI]
        "error-solid": "bg-destructive text-on-error", // [FORCE-UI]
        outline: "border-border text-foreground",
        ghost: "hover:bg-interactive-hover hover:text-foreground",
        link: "text-link underline-offset-4 hover:underline",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

function Badge({
  className,
  variant = "default",
  asChild = false,
  ...props
}: React.ComponentProps<"span"> &
  VariantProps<typeof badgeVariants> & { asChild?: boolean }) {
  const Comp = asChild ? Slot.Root : "span"

  return (
    <Comp
      data-slot="badge"
      data-variant={variant}
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  )
}

export { Badge, badgeVariants }

// packages/registry-svelte/ui/badge/badge.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from "tailwind-variants";

	export const badgeVariants = tv({
		base: "cn-badge focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive group/badge inline-flex w-fit shrink-0 items-center justify-center overflow-hidden whitespace-nowrap transition-colors focus-visible:ring-[3px] [&>svg]:pointer-events-none",
		variants: {
			variant: {
				default: "cn-badge-variant-default",
				secondary: "cn-badge-variant-secondary",
				destructive: "cn-badge-variant-destructive",
				warning: "cn-badge-variant-warning",
				success: "cn-badge-variant-success",
				info: "cn-badge-variant-info",
				"success-solid": "cn-badge-variant-success-solid",
				"warning-solid": "cn-badge-variant-warning-solid",
				"info-solid": "cn-badge-variant-info-solid",
				"error-solid": "cn-badge-variant-error-solid",
				outline: "cn-badge-variant-outline",
				ghost: "cn-badge-variant-ghost",
				link: "cn-badge-variant-link",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	});

	export type BadgeVariant = VariantProps<typeof badgeVariants>["variant"];
</script>

<script lang="ts">
	import type { HTMLAnchorAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		href,
		class: className,
		variant = "default",
		srLabel,
		children,
		...restProps
	}: WithElementRef<HTMLAnchorAttributes> & {
		variant?: BadgeVariant;
		/**
		 * [FORCE-UI] Visually-hidden text prefix announced before the badge's
		 * content. Status is otherwise conveyed only through color, which a
		 * screen reader can't perceive — set this on count- or glyph-only
		 * badges (e.g. `srLabel="Synced versions:"` on a bare "42").
		 */
		srLabel?: string;
	} = $props();
</script>

<svelte:element
	this={href ? "a" : "span"}
	bind:this={ref}
	data-slot="badge"
	{href}
	class={cn(badgeVariants({ variant }), className)}
	{...restProps}
>
	{#if !href && srLabel}<span class="sr-only">{srLabel}&nbsp;</span>{/if}
	{@render children?.()}
</svelte:element>
