// packages/registry-svelte/ui/message-scroller/message-scroller-viewport.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";
	import {
		getMessageScrollerContext,
		getMessageScrollerController,
	} from "./context.js";

	let {
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();

	const scroller = $derived(
		getMessageScrollerContext("MessageScroller.Viewport")
	);
	const controller = getMessageScrollerController();

	let viewportEl: HTMLDivElement | null = $state(null);

	function distanceFromEdges(el: HTMLDivElement) {
		return {
			start: el.scrollTop,
			end: el.scrollHeight - el.clientHeight - el.scrollTop,
		};
	}

	function updateEdges() {
		if (!viewportEl || !controller) return;
		const { start, end } = distanceFromEdges(viewportEl);
		controller.setEdges(
			start <= scroller.scrollEdgeThreshold,
			end <= scroller.scrollEdgeThreshold
		);
	}

	function scrollTo(direction: "start" | "end") {
		if (!viewportEl) return;
		viewportEl.scrollTo({
			top: direction === "end" ? viewportEl.scrollHeight : 0,
			behavior: "smooth",
		});
	}

	function followToEnd() {
		if (!viewportEl || !scroller.autoScroll) return;
		const { end } = distanceFromEdges(viewportEl);
		// follow appends only while the user is already near the bottom
		if (end <= Math.max(scroller.scrollEdgeThreshold, 160)) {
			viewportEl.scrollTo({ top: viewportEl.scrollHeight });
		}
	}

	$effect(() => {
		controller?.registerScrollTo(scrollTo);
	});

	onMount(() => {
		if (!viewportEl) return;
		updateEdges();
		// auto-follow: react to appended items / growing content
		const observer = new MutationObserver(() => {
			requestAnimationFrame(() => {
				followToEnd();
				updateEdges();
			});
		});
		observer.observe(viewportEl, {
			childList: true,
			subtree: true,
			characterData: true,
		});
		return () => observer.disconnect();
	});
</script>

<div
	bind:this={viewportEl}
	data-slot="message-scroller-viewport"
	onscroll={updateEdges}
	class={cn(
		"cn-message-scroller-viewport size-full min-h-0 min-w-0 scroll-fade-b scrollbar-thin scrollbar-gutter-stable overflow-y-auto overscroll-contain contain-content data-autoscrolling:scrollbar-thumb-transparent data-autoscrolling:scrollbar-track-transparent",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>

// packages/registry-vue/ui/message-scroller/MessageScrollerViewport.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue"
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"
import {
  useMessageScrollerContext,
  useMessageScrollerController,
} from "./context"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()

const scroller = useMessageScrollerContext("MessageScrollerViewport")
const controller = useMessageScrollerController()

const viewportEl = ref<HTMLDivElement | null>(null)

function distanceFromEdges(el: HTMLDivElement) {
  return {
    start: el.scrollTop,
    end: el.scrollHeight - el.clientHeight - el.scrollTop,
  }
}

function updateEdges() {
  const el = viewportEl.value
  if (!el || !controller) return
  const { start, end } = distanceFromEdges(el)
  controller.setEdges(
    start <= scroller.scrollEdgeThreshold,
    end <= scroller.scrollEdgeThreshold
  )
}

function scrollTo(direction: "start" | "end") {
  const el = viewportEl.value
  if (!el) return
  el.scrollTo({
    top: direction === "end" ? el.scrollHeight : 0,
    behavior: "smooth",
  })
}

function followToEnd() {
  const el = viewportEl.value
  if (!el || !scroller.autoScroll) return
  const { end } = distanceFromEdges(el)
  // follow appends only while the user is already near the bottom
  if (end <= Math.max(scroller.scrollEdgeThreshold, 160)) {
    el.scrollTo({ top: el.scrollHeight })
  }
}

let observer: MutationObserver | null = null

onMounted(() => {
  const el = viewportEl.value
  if (!el) return
  controller?.registerScrollTo(scrollTo)
  updateEdges()
  // auto-follow: react to appended items / growing content
  observer = new MutationObserver(() => {
    requestAnimationFrame(() => {
      followToEnd()
      updateEdges()
    })
  })
  observer.observe(el, {
    childList: true,
    subtree: true,
    characterData: true,
  })
})

onBeforeUnmount(() => observer?.disconnect())
</script>

<template>
  <div
    ref="viewportEl"
    data-slot="message-scroller-viewport"
    @scroll="updateEdges"
    :class="
      cn(
        'cn-message-scroller-viewport size-full min-h-0 min-w-0 scroll-fade-b scrollbar-thin scrollbar-gutter-stable overflow-y-auto overscroll-contain contain-content data-autoscrolling:scrollbar-thumb-transparent data-autoscrolling:scrollbar-track-transparent',
        props.class
      )
    "
  >
    <slot />
  </div>
</template>
