// packages/registry-vue/blocks/sidebar-06/NavMain.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-06
import MoreHorizontal from '@material-symbols/svg-400/rounded/more_horiz.svg?component'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/ui/dropdown-menu'
import {
  SidebarGroup,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from '@/ui/sidebar'

const props = defineProps<{
  items: {
    title: string
    url: string
    isActive?: boolean
    items?: {
      title: string
      url: string
    }[]
  }[]
}>()

const { isMobile } = useSidebar()
</script>

<template>
  <SidebarGroup>
    <SidebarMenu>
      <DropdownMenu v-for="item in props.items" :key="item.title">
        <SidebarMenuItem>
          <DropdownMenuTrigger as-child>
            <SidebarMenuButton class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground">
              {{ item.title }}
              <MoreHorizontal class="ml-auto" />
            </SidebarMenuButton>
          </DropdownMenuTrigger>
          <DropdownMenuContent
            v-if="item.items?.length"
            :side="isMobile ? 'bottom' : 'right'"
            :align="isMobile ? 'end' : 'start'"
            class="min-w-56 rounded-lg"
          >
            <DropdownMenuItem v-for="child in item.items" :key="child.title" as-child>
              <a :href="child.url">{{ child.title }}</a>
            </DropdownMenuItem>
          </DropdownMenuContent>
        </SidebarMenuItem>
      </DropdownMenu>
    </SidebarMenu>
  </SidebarGroup>
</template>

// packages/registry-svelte/blocks/sidebar-06/components/nav-main.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-06 -->
<script lang="ts">
  import MoreHorizontal from "~icons/ms/more_horiz"
  import * as DropdownMenu from "$lib/registry/ui/dropdown-menu/index.js"
  import { useSidebar } from "$lib/registry/ui/sidebar/context.svelte.js"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  let {
    items,
  }: {
    items: {
      title: string
      url: string
      items?: { title: string; url: string }[]
    }[]
  } = $props()

  const sidebar = useSidebar()
</script>

<Sidebar.Group>
  <Sidebar.Menu>
    {#each items as item (item.title)}
      <DropdownMenu.Root>
        <Sidebar.MenuItem>
          <DropdownMenu.Trigger>
            {#snippet child({ props })}
              <Sidebar.MenuButton
                class="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
                {...props}
              >
                {item.title}
                <MoreHorizontal class="ml-auto" />
              </Sidebar.MenuButton>
            {/snippet}
          </DropdownMenu.Trigger>
          {#if item.items?.length}
            <DropdownMenu.Content
              side={sidebar.isMobile ? "bottom" : "right"}
              align={sidebar.isMobile ? "end" : "start"}
              class="min-w-56 rounded-lg"
            >
              {#each item.items as subItem (subItem.title)}
                <DropdownMenu.Item>
                  {#snippet child({ props })}
                    <a href={subItem.url} {...props}>{subItem.title}</a>
                  {/snippet}
                </DropdownMenu.Item>
              {/each}
            </DropdownMenu.Content>
          {/if}
        </Sidebar.MenuItem>
      </DropdownMenu.Root>
    {/each}
  </Sidebar.Menu>
</Sidebar.Group>
