// packages/registry-vue/ui/message-scroller/MessageScrollerProvider.vue
<script setup lang="ts">
import { reactive, ref } from "vue"
import {
  provideMessageScrollerContext,
  provideMessageScrollerController,
  type MessageScrollerState,
  type MessageScrollerProviderProps,
} from "./context"

const props = withDefaults(defineProps<MessageScrollerProviderProps>(), {
  autoScroll: true,
  scrollEdgeThreshold: 80,
})

let viewportScrollTo: (direction: "start" | "end") => void = () => {}

const atStart = ref(false)
const atEnd = ref(false)

provideMessageScrollerController({
  setEdges(start: boolean, end: boolean) {
    atStart.value = start
    atEnd.value = end
  },
  registerScrollTo(fn: (direction: "start" | "end") => void) {
    viewportScrollTo = fn
  },
})

const state: MessageScrollerState = reactive({
  get autoScroll() {
    return props.autoScroll
  },
  get scrollEdgeThreshold() {
    return props.scrollEdgeThreshold
  },
  get atStart() {
    return atStart.value
  },
  get atEnd() {
    return atEnd.value
  },
  scrollTo: (direction) => viewportScrollTo(direction),
})
provideMessageScrollerContext(state)
</script>

<template>
  <slot />
</template>

// packages/registry-svelte/ui/message-scroller/message-scroller-provider.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import {
		setMessageScrollerContext,
		setMessageScrollerController,
		type MessageScrollerState,
		type MessageScrollerProviderProps,
	} from "./context.js";

	let {
		autoScroll = true,
		scrollEdgeThreshold = 80,
		children,
	}: MessageScrollerProviderProps & { children?: Snippet } = $props();

	let atStart = $state(false);
	let atEnd = $state(false);
	let viewportScrollTo: (direction: "start" | "end") => void = () => {};

	setMessageScrollerController({
		setEdges(start: boolean, end: boolean) {
			atStart = start;
			atEnd = end;
		},
		registerScrollTo(fn: (direction: "start" | "end") => void) {
			viewportScrollTo = fn;
		},
	});

	const scrollerState: MessageScrollerState = {
		get autoScroll() {
			return autoScroll;
		},
		get scrollEdgeThreshold() {
			return scrollEdgeThreshold;
		},
		get atStart() {
			return atStart;
		},
		get atEnd() {
			return atEnd;
		},
		scrollTo: (direction) => viewportScrollTo(direction),
	};

	setMessageScrollerContext(scrollerState);
</script>

{@render children?.()}
