// packages/registry-vue/ui/message-scroller/MessageScrollerItem.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = withDefaults(
  defineProps<{
    class?: HTMLAttributes["class"]
    messageId?: string
    scrollAnchor?: boolean
  }>(),
  {
    scrollAnchor: false,
  }
)
</script>

<template>
  <div
    data-slot="message-scroller-item"
    :data-message-id="props.messageId"
    :data-scroll-anchor="props.scrollAnchor ? 'true' : undefined"
    :class="
      cn(
        'cn-message-scroller-item min-w-0 shrink-0 [contain-intrinsic-size:auto_10rem] [content-visibility:auto]',
        props.class
      )
    "
  >
    <slot />
  </div>
</template>

// packages/registry-svelte/ui/message-scroller/message-scroller-item.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		messageId,
		scrollAnchor = false,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		messageId?: string;
		scrollAnchor?: boolean;
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="message-scroller-item"
	data-message-id={messageId}
	data-scroll-anchor={scrollAnchor ? "true" : undefined}
	class={cn(
		"cn-message-scroller-item min-w-0 shrink-0 [contain-intrinsic-size:auto_10rem] [content-visibility:auto]",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>
