// packages/registry-vue/blocks/sidebar-11/AppSidebar.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-11
import File from '@material-symbols/svg-400/rounded/description.svg?component'
import TreeItem from './TreeItem.vue'
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarRail,
} from '@/ui/sidebar'

// This is sample data.
interface TreeNode {
  name: string
  children?: TreeNode[]
}

const data = {
  changes: [
    { file: 'README.md', state: 'M' },
    { file: 'api/hello/route.ts', state: 'U' },
    { file: 'app/layout.tsx', state: 'M' },
  ],
  tree: [
    {
      name: 'app',
      children: [
        { name: 'api', children: [{ name: 'hello', children: [{ name: 'route.ts' }] }] },
        { name: 'page.tsx' },
        { name: 'layout.tsx' },
        { name: 'blog', children: [{ name: 'page.tsx' }] },
      ],
    },
    {
      name: 'components',
      children: [
        { name: 'ui', children: [{ name: 'button.tsx' }, { name: 'card.tsx' }] },
        { name: 'header.tsx' },
        { name: 'footer.tsx' },
      ],
    },
    { name: 'lib', children: [{ name: 'util.ts' }] },
    { name: 'public', children: [{ name: 'favicon.ico' }, { name: 'vercel.svg' }] },
    { name: '.eslintrc.json' },
    { name: '.gitignore' },
    { name: 'next.config.js' },
    { name: 'tailwind.config.js' },
    { name: 'package.json' },
    { name: 'README.md' },
  ] as TreeNode[],
}
</script>

<template>
  <Sidebar>
    <SidebarContent>
      <SidebarGroup>
        <SidebarGroupLabel>Changes</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <SidebarMenuItem v-for="(item, index) in data.changes" :key="index">
              <SidebarMenuButton>
                <File />
                {{ item.file }}
              </SidebarMenuButton>
              <SidebarMenuBadge>{{ item.state }}</SidebarMenuBadge>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
      <SidebarGroup>
        <SidebarGroupLabel>Files</SidebarGroupLabel>
        <SidebarGroupContent>
          <SidebarMenu>
            <TreeItem v-for="(item, index) in data.tree" :key="index" :item="item" />
          </SidebarMenu>
        </SidebarGroupContent>
      </SidebarGroup>
    </SidebarContent>
    <SidebarRail />
  </Sidebar>
</template>

// packages/registry-svelte/blocks/sidebar-11/components/app-sidebar.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-11 -->
<script lang="ts">
  import FileIcon from "~icons/ms/description"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  import Tree from "./tree.svelte"

  type TreeItem = string | TreeItem[]

  const changes = [
    { state: "modified", file: "app/layout.tsx" },
    { state: "modified", file: "components/ui/button.tsx" },
  ]

  const files: TreeItem[] = [
    "package.json",
    "tsconfig.json",
    [
      "app",
      ["page.tsx", "layout.tsx"],
      ["components", ["button.tsx", "card.tsx"]],
    ],
  ]
</script>

<Sidebar.Root>
  <Sidebar.Content>
    <Sidebar.Group>
      <Sidebar.GroupLabel>Changes</Sidebar.GroupLabel>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          {#each changes as change, index (index)}
            <Sidebar.MenuItem>
              <Sidebar.MenuButton>
                <FileIcon />
                {change.file}
              </Sidebar.MenuButton>
              <Sidebar.MenuBadge>{change.state}</Sidebar.MenuBadge>
            </Sidebar.MenuItem>
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
    <Sidebar.Group>
      <Sidebar.GroupLabel>Files</Sidebar.GroupLabel>
      <Sidebar.GroupContent>
        <Sidebar.Menu>
          {#each files as item, index (index)}
            <Tree {item} />
          {/each}
        </Sidebar.Menu>
      </Sidebar.GroupContent>
    </Sidebar.Group>
  </Sidebar.Content>
  <Sidebar.Rail />
</Sidebar.Root>
