// packages/registry-vue/ui/marker/MarkerContent.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <span
    data-slot="marker-content"
    :class="cn('cn-marker-content min-w-0 wrap-break-word', props.class)"
  >
    <slot />
  </span>
</template>

// packages/registry-svelte/ui/marker/marker-content.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLSpanElement>> = $props();
</script>

<span
	bind:this={ref}
	data-slot="marker-content"
	class={cn("cn-marker-content min-w-0 wrap-break-word", className)}
	{...restProps}
>
	{@render children?.()}
</span>
