// apps/preview-vue/src/vue/alert-rtl.vue
<script setup lang="ts">
import { Alert, AlertDescription, AlertTitle } from "@/ui/alert"
import CheckCircle2Icon from "@material-symbols/svg-400/rounded/check_circle.svg?component"
import InfoIcon from "@material-symbols/svg-400/rounded/info.svg?component"
</script>

<template>
  <div class="grid w-full max-w-md items-start gap-4" dir="rtl">
    <Alert>
      <CheckCircle2Icon />
      <AlertTitle>تم الدفع بنجاح</AlertTitle>
      <AlertDescription>
        تمت معالجة دفعتك البالغة 29.99 دولارًا. تم إرسال إيصال إلى عنوان بريدك
        الإلكتروني.
      </AlertDescription>
    </Alert>
    <Alert>
      <InfoIcon />
      <AlertTitle>ميزة جديدة متاحة</AlertTitle>
      <AlertDescription>
        لقد أضفنا دعم الوضع الداكن. يمكنك تفعيله في إعدادات حسابك.
      </AlertDescription>
    </Alert>
  </div>
</template>

// apps/preview-svelte/src/svelte/alert-rtl.svelte
<script lang="ts">
	import * as Alert from "@/svelte-ui/alert/index.js";
	import CheckCircle2Icon from "~icons/ms/check_circle";
	import InfoIcon from "~icons/ms/info";
</script>

<div class="grid w-full max-w-md items-start gap-4" dir="rtl">
	<Alert.Root>
		<CheckCircle2Icon />
		<Alert.Title>تم الدفع بنجاح</Alert.Title>
		<Alert.Description>
			تمت معالجة دفعتك البالغة 29.99 دولارًا. تم إرسال إيصال إلى عنوان بريدك الإلكتروني.
		</Alert.Description>
	</Alert.Root>
	<Alert.Root>
		<InfoIcon />
		<Alert.Title>ميزة جديدة متاحة</Alert.Title>
		<Alert.Description>
			لقد أضفنا دعم الوضع الداكن. يمكنك تفعيله في إعدادات حسابك.
		</Alert.Description>
	</Alert.Root>
</div>
