// apps/preview-vue/src/vue/bubble-alignment.vue
<script setup lang="ts">
import { Bubble, BubbleContent } from '@/ui/bubble'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Bubble variant="muted">
      <BubbleContent>
        This bubble is aligned to the start. This is the default alignment.
      </BubbleContent>
    </Bubble>
    <Bubble align="end">
      <BubbleContent>
        This bubble is aligned to the end. Use this for user messages.
      </BubbleContent>
    </Bubble>
  </div>
</template>

// apps/preview-svelte/src/svelte/bubble-alignment.svelte
<script lang="ts">
	import { Bubble, BubbleContent } from "@/svelte-ui/bubble/index.js";
</script>

<div class="flex w-full max-w-sm flex-col gap-8 py-12">
	<Bubble variant="muted">
		<BubbleContent>
			This bubble is aligned to the start. This is the default alignment.
		</BubbleContent>
	</Bubble>
	<Bubble align="end">
		<BubbleContent>
			This bubble is aligned to the end. Use this for user messages.
		</BubbleContent>
	</Bubble>
</div>
