// packages/registry-vue/examples/context-menu/ContextMenuSides.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from '@/ui/context-menu'

const side = ref('top')

// static classes so Tailwind's JIT keeps them
const zones = [
  { side: 'top', zone: 'col-start-1 col-span-3 row-start-1 items-start' },
  { side: 'right', zone: 'col-start-3 col-span-1 row-start-2 row-span-2 items-center justify-end' },
  { side: 'bottom', zone: 'col-start-1 col-span-3 row-start-4 items-end' },
  { side: 'left', zone: 'col-start-1 col-span-1 row-start-2 row-span-2 items-center justify-start' },
] as const
</script>

<template>
  <div class="flex flex-col gap-2">
    <div class="grid h-64 w-full max-w-md grid-cols-3 grid-rows-4 gap-1">
      <ContextMenu v-for="z in zones" :key="z.side">
        <ContextMenuTrigger as-child>
          <div
            class="flex cursor-default rounded-md border border-dashed p-2 text-sm text-muted-foreground"
            :class="z.zone"
          >
            Right click — {{ z.side }}
          </div>
        </ContextMenuTrigger>
        <ContextMenuContent :side="z.side">
          <ContextMenuItem @select="side = z.side">Undo</ContextMenuItem>
          <ContextMenuItem>Redo</ContextMenuItem>
        </ContextMenuContent>
      </ContextMenu>
    </div>
    <p class="text-xs text-muted-foreground">Last opened from the {{ side }} side.</p>
  </div>
</template>

// apps/preview-svelte/src/svelte/context-menu-sides.svelte
<script lang="ts">
	import * as ContextMenu from "@/svelte-ui/context-menu/index.js";

	const sides = [
		{ side: "top", fine: "Right click (top)", coarse: "Long press (top)" },
		{ side: "right", fine: "Right click (right)", coarse: "Long press (right)" },
		{ side: "bottom", fine: "Right click (bottom)", coarse: "Long press (bottom)" },
		{ side: "left", fine: "Right click (left)", coarse: "Long press (left)" },
	] as const;
</script>

<div class="grid w-full max-w-sm grid-cols-2 gap-4">
	{#each sides as { side, fine, coarse } (side)}
		<ContextMenu.Root>
			<ContextMenu.Trigger
				class="flex aspect-video w-full max-w-xs items-center justify-center rounded-xl border border-dashed text-sm"
			>
				<span class="pointer-coarse:hidden">{fine}</span>
				<span class="pointer-fine:hidden">{coarse}</span>
			</ContextMenu.Trigger>
			<ContextMenu.Content {side}>
				<ContextMenu.Group>
					<ContextMenu.Item>Back</ContextMenu.Item>
					<ContextMenu.Item>Forward</ContextMenu.Item>
					<ContextMenu.Item>Reload</ContextMenu.Item>
				</ContextMenu.Group>
			</ContextMenu.Content>
		</ContextMenu.Root>
	{/each}
</div>
