// apps/preview-vue/src/vue/drawer-snap-points.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import {
  Drawer,
  DrawerContent,
  DrawerDescription,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/ui/drawer"
import { ref } from "vue"

const snapPoints = [0.35, 0.65, 1]
const activeSnap = ref<number | string | null>(snapPoints[0])
</script>

<template>
  <Drawer v-model:active-snap-point="activeSnap" :snap-points="snapPoints">
    <DrawerTrigger as-child>
      <Button variant="outline">Drawer with snap points</Button>
    </DrawerTrigger>
    <DrawerContent class="h-[85vh]">
      <DrawerHeader>
        <DrawerTitle>Snap points</DrawerTitle>
        <DrawerDescription
          >Drag the drawer between three heights.</DrawerDescription
        >
      </DrawerHeader>
      <div
        class="flex flex-1 flex-col items-center justify-center gap-2 p-4 text-muted-foreground"
      >
        <p>
          Active snap point: {{ snapPoints.indexOf(Number(activeSnap)) + 1 }} /
          {{ snapPoints.length }}
        </p>
        <ul class="list-disc pl-5 text-left text-sm">
          <li>Peek (35%)</li>
          <li>Half (65%)</li>
          <li>Full (100%)</li>
        </ul>
      </div>
    </DrawerContent>
  </Drawer>
</template>

// apps/preview-svelte/src/svelte/drawer-snap-points.svelte
<script lang="ts">
	import { Button, buttonVariants } from "@/svelte-ui/button/index.js";
	import * as Drawer from "@/svelte-ui/drawer/index.js";

	const snapPoints = [0.35, 0.65, 1];
	let activeSnapPoint = $state<number | string | null>(snapPoints[0]);
</script>

<div class="flex flex-col items-center gap-4">
	<p class="text-muted-foreground text-sm text-center max-w-sm">
		Drag the drawer between snap points. Currently snapped to{" "}
		{Math.round((Number(activeSnapPoint) || 0) * 100)}% of the screen.
	</p>
	<Drawer.Root bind:activeSnapPoint snapPoints={snapPoints} fadeFromIndex={snapPoints.length - 1}>
		<Drawer.Trigger class={buttonVariants({ variant: "outline" })}>
			Open drawer with snap points
		</Drawer.Trigger>
		<Drawer.Content>
			<div class="mx-auto flex w-full max-w-sm flex-col items-center gap-1 pb-4">
				<Drawer.Header class="items-center">
					<Drawer.Title>Snap points</Drawer.Title>
					<Drawer.Description>Drag up and down to switch.</Drawer.Description>
				</Drawer.Header>
				<div class="flex gap-2 py-4">
					{#each snapPoints as point, i (i)}
						<Button
							variant="outline"
							size="sm"
							onclick={() => (activeSnapPoint = point)}
						>
							{Math.round(point * 100)}%
						</Button>
					{/each}
				</div>
				<Drawer.Footer class="w-full">
					<Drawer.Close class={buttonVariants({ variant: "outline" })}>
						Close
					</Drawer.Close>
				</Drawer.Footer>
			</div>
		</Drawer.Content>
	</Drawer.Root>
</div>
