// packages/registry-vue/examples/drawer/DrawerNonModal.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '@/ui/drawer'
import { Button } from '@/ui/button'

const open = ref(false)
</script>

<template>
  <div class="flex flex-col items-start gap-4">
    <p class="text-sm text-muted-foreground">
      While this drawer is open you can still interact with the page — it is non-modal.
    </p>
    <Drawer v-model:open="open" :modal="false">
      <DrawerTrigger as-child>
        <Button variant="outline">Open non-modal drawer</Button>
      </DrawerTrigger>
      <DrawerContent>
        <DrawerHeader>
          <DrawerTitle>Non-modal drawer</DrawerTitle>
          <DrawerDescription>No overlay; the rest of the page stays interactive.</DrawerDescription>
        </DrawerHeader>
        <DrawerFooter>
          <DrawerClose as-child>
            <Button variant="outline">Close</Button>
          </DrawerClose>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  </div>
</template>

// apps/preview-svelte/src/svelte/drawer-non-modal.svelte
<script lang="ts">
	import { Button, buttonVariants } from "@/svelte-ui/button/index.js";
	import * as Drawer from "@/svelte-ui/drawer/index.js";

	let open = $state(false);
</script>

<div class="flex flex-col items-start gap-4">
	<p class="text-muted-foreground text-sm">
		Non-modal drawers let you interact with the rest of the page while open —
		no overlay, no scroll lock.
	</p>
	<Button variant="outline" onclick={() => (open = !open)}>
		{open ? "Close drawer" : "Open drawer"}
	</Button>
	<Drawer.Root bind:open modal={false}>
		<Drawer.Content class="mb-0 flex flex-col rounded-t-[10px]">
			<div class="mx-auto w-full max-w-sm">
				<Drawer.Header>
					<Drawer.Title>Non-modal drawer</Drawer.Title>
					<Drawer.Description>
						The page behind stays fully interactive.
					</Drawer.Description>
				</Drawer.Header>
				<Drawer.Footer>
					<Drawer.Close class={buttonVariants({ variant: "outline" })}>
						Close
					</Drawer.Close>
				</Drawer.Footer>
			</div>
		</Drawer.Content>
	</Drawer.Root>
</div>
