// apps/preview-vue/src/vue/marker-variants.vue
<script setup lang="ts">
import {
  Marker,
  MarkerContent,
} from '@/ui/marker'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Marker>
      <MarkerContent>A default marker for inline notes.</MarkerContent>
    </Marker>
    <Marker variant="separator">
      <MarkerContent>A separator marker</MarkerContent>
    </Marker>
    <Marker variant="border">
      <MarkerContent>A border marker for row boundaries.</MarkerContent>
    </Marker>
  </div>
</template>

// apps/preview-svelte/src/svelte/marker-variants.svelte
<script lang="ts">
	import { Marker, MarkerContent } from "@/svelte-ui/marker/index.js";
</script>

<div class="flex w-full max-w-sm flex-col gap-8 py-12">
	<Marker>
		<MarkerContent>A default marker for inline notes.</MarkerContent>
	</Marker>
	<Marker variant="separator">
		<MarkerContent>A separator marker</MarkerContent>
	</Marker>
	<Marker variant="border">
		<MarkerContent>A border marker for row boundaries.</MarkerContent>
	</Marker>
</div>
