// packages/registry-vue/examples/marker/MarkerStatus.vue
<script setup lang="ts">
import { Spinner } from '@/ui/spinner'
import {
  Marker,
  MarkerContent,
  MarkerIcon,
} from '@/ui/marker'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Marker role="status">
      <MarkerIcon>
        <Spinner />
      </MarkerIcon>
      <MarkerContent>Compacting conversation</MarkerContent>
    </Marker>
    <Marker variant="separator" role="status">
      <MarkerIcon>
        <Spinner />
      </MarkerIcon>
      <MarkerContent>Running tests</MarkerContent>
    </Marker>
  </div>
</template>

// apps/preview-svelte/src/svelte/marker-status.svelte
<script lang="ts">
	import {
		Marker,
		MarkerContent,
		MarkerIcon,
	} from "@/svelte-ui/marker/index.js";
	import { Spinner } from "@/svelte-ui/spinner/index.js";
</script>

<div class="flex w-full max-w-sm flex-col gap-8 py-12">
	<Marker role="status">
		<MarkerIcon><Spinner /></MarkerIcon>
		<MarkerContent>Compacting conversation</MarkerContent>
	</Marker>
	<Marker variant="separator" role="status">
		<MarkerIcon><Spinner /></MarkerIcon>
		<MarkerContent>Running tests</MarkerContent>
	</Marker>
</div>
