// packages/registry-vue/examples/message-scroller/MessageScrollerState.vue
<script setup lang="ts">
import { defineComponent, h, ref } from 'vue'
import {
  MessageScrollerProvider,
  MessageScroller,
  MessageScrollerViewport,
  MessageScrollerContent,
  MessageScrollerItem,
  MessageScrollerButton,
  useMessageScrollerContext,
} from '@/ui/message-scroller'
import { Badge } from '@/ui/badge'

const messages = ref(
  Array.from({ length: 24 }, (_, i) => ({
    id: i,
    text: `Message ${i + 1} — scroll to watch the edge state change.`,
  })),
)

// reads atStart/atEnd from the provider and mirrors them into badges
const EdgeState = defineComponent({
  setup() {
    const state = useMessageScrollerContext('EdgeState')
    return () => [
      h(Badge, { variant: state.atStart ? 'default' : 'outline' }, () => 'at start'),
      h(Badge, { variant: state.atEnd ? 'default' : 'outline' }, () => 'at end'),
    ]
  },
})
</script>

<template>
  <MessageScrollerProvider>
    <div class="mx-auto flex w-full max-w-sm flex-col gap-4">
      <div class="flex items-center gap-2">
        <component :is="EdgeState" />
      </div>
      <MessageScroller class="h-96 rounded-xl border bg-card">
        <MessageScrollerViewport>
          <MessageScrollerContent class="gap-2 p-4">
            <MessageScrollerItem v-for="message in messages" :key="message.id" class="text-sm text-muted-foreground">
              {{ message.text }}
            </MessageScrollerItem>
          </MessageScrollerContent>
        </MessageScrollerViewport>
        <MessageScrollerButton />
      </MessageScroller>
    </div>
  </MessageScrollerProvider>
</template>

// apps/preview-svelte/src/svelte/message-scroller-state.svelte
<script lang="ts">
	import {
		MessageScrollerProvider,
		MessageScroller,
		MessageScrollerViewport,
		MessageScrollerContent,
		MessageScrollerItem,
		MessageScrollerButton,
	} from "@/svelte-ui/message-scroller/index.js";
	import StateIndicator from "./message-scroller-state/state-indicator.svelte";

	type Msg = { id: number; role: "user" | "assistant"; text: string };

	const seed: [Msg["role"], string][] = [
		["user", "First message of a long thread."],
		["assistant", "Second message — scroll around and watch the pills update."],
		["user", "Third message."],
		["assistant", "Fourth message. The indicator shows which edge you're at."],
	];

	let messages = $state<Msg[]>(seed.map(([role, text], i) => ({ id: i, role, text })));
</script>

<MessageScrollerProvider>
	<div class="mx-auto flex w-full max-w-sm flex-col gap-4">
		<StateIndicator />
		<div class="rounded-xl border bg-card">
			<MessageScroller class="h-80">
				<MessageScrollerViewport>
					<MessageScrollerContent class="p-4 gap-2">
						{#each messages as message (message.id)}
							<MessageScrollerItem>
								<span
									class="inline-block max-w-[85%] rounded-lg px-3 py-2 text-sm
										{message.role === 'user'
										? 'ml-auto bg-primary text-primary-foreground'
										: 'bg-muted'}"
								>
									{message.text}
								</span>
							</MessageScrollerItem>
						{/each}
					</MessageScrollerContent>
				</MessageScrollerViewport>
				<MessageScrollerButton />
			</MessageScroller>
		</div>
	</div>
</MessageScrollerProvider>
