// apps/preview-angular/src/angular/message-demo.ts
import { Avatar, AvatarFallback, AvatarImage } from "@/angular-ui/avatar"
import { Bubble, BubbleContent, BubbleGroup, BubbleReactions } from "@/angular-ui/bubble"
import { Marker, MarkerContent } from "@/angular-ui/marker"
import { Message, MessageAvatar, MessageContent, MessageFooter } from "@/angular-ui/message"
import { Component } from "@angular/core"

// apps/v4/examples/base/message-demo.tsx
@Component({
  selector: "preview-message-demo",
  standalone: true,
  imports: [Message, MessageAvatar, MessageContent, MessageFooter, Avatar, AvatarImage, AvatarFallback, Bubble, BubbleContent, BubbleGroup, BubbleReactions, Marker, MarkerContent],
  template: `
    <div class="flex w-full max-w-sm flex-col gap-6 py-12">
      <div uiMessage align="end">
        <div uiMessageAvatar>
          <span uiAvatar>
            <img uiAvatarImage src="/avatars/10.png" alt="@me" />
            <span uiAvatarFallback>ME</span>
          </span>
        </div>
        <div uiMessageContent>
          <div uiBubble><div uiBubbleContent>Deploying to prod real quick.</div></div>
        </div>
      </div>
      <div uiMessage>
        <div uiMessageAvatar>
          <span uiAvatar>
            <img uiAvatarImage src="/avatars/02.png" alt="@rabbit" />
            <span uiAvatarFallback>R</span>
          </span>
        </div>
        <div uiMessageContent>
          <div uiBubble variant="muted"><div uiBubbleContent>It's 4:55 PM. On a Friday.</div></div>
        </div>
      </div>
      <div uiMessage align="end">
        <div uiMessageAvatar>
          <span uiAvatar>
            <img uiAvatarImage src="/avatars/10.png" alt="@me" />
            <span uiAvatarFallback>ME</span>
          </span>
        </div>
        <div uiMessageContent>
          <div uiBubble><div uiBubbleContent>It's a one-line change.</div></div>
          <div uiMessageFooter>Delivered</div>
        </div>
      </div>
      <div uiMessage>
        <div uiMessageAvatar>
          <span uiAvatar>
            <img uiAvatarImage src="/avatars/02.png" alt="@rabbit" />
            <span uiAvatarFallback>R</span>
          </span>
        </div>
        <div uiMessageContent>
          <div uiBubbleGroup>
            <div uiBubble variant="muted">
              <div uiBubbleContent>It's always a one-line change 😭.</div>
            </div>
            <div uiBubble variant="muted">
              <div uiBubbleContent>Alright, let me take a look.</div>
              <div uiBubbleReactions aria-label="Reactions: thumbs up"><span>👍</span></div>
            </div>
          </div>
        </div>
      </div>
      <div uiMarker role="status">
        <div uiMarkerContent class="shimmer"><span class="font-medium">Oliver</span> is typing...</div>
      </div>
    </div>
  `,
})
export class MessageDemoComponent {}

export default MessageDemoComponent

// apps/preview-svelte/src/svelte/message-demo.svelte
<script lang="ts">
	import * as Avatar from "@/svelte-ui/avatar/index.js";
	import {
		Bubble,
		BubbleContent,
		BubbleGroup,
		BubbleReactions,
	} from "@/svelte-ui/bubble/index.js";
	import { Marker, MarkerContent } from "@/svelte-ui/marker/index.js";
	import {
		Message,
		MessageAvatar,
		MessageContent,
		MessageFooter,
	} from "@/svelte-ui/message/index.js";
</script>

<div class="flex w-full max-w-sm flex-col gap-6 py-12">
	<Message align="end">
		<MessageAvatar>
			<Avatar.Root>
				<Avatar.Image src="https://github.com/evilrabbit.png" alt="@me" />
				<Avatar.Fallback>ME</Avatar.Fallback>
			</Avatar.Root>
		</MessageAvatar>
		<MessageContent>
			<Bubble>
				<BubbleContent>Deploying to prod real quick.</BubbleContent>
			</Bubble>
		</MessageContent>
	</Message>
	<Message>
		<MessageAvatar>
			<Avatar.Root>
				<Avatar.Image src="https://github.com/shadcn.png" alt="@rabbit" />
				<Avatar.Fallback>R</Avatar.Fallback>
			</Avatar.Root>
		</MessageAvatar>
		<MessageContent>
			<Bubble variant="muted">
				<BubbleContent>It's 4:55 PM. On a Friday.</BubbleContent>
			</Bubble>
		</MessageContent>
	</Message>
	<Message align="end">
		<MessageAvatar>
			<Avatar.Root>
				<Avatar.Image src="https://github.com/evilrabbit.png" alt="@me" />
				<Avatar.Fallback>ME</Avatar.Fallback>
			</Avatar.Root>
		</MessageAvatar>
		<MessageContent>
			<Bubble>
				<BubbleContent>It's a one-line change.</BubbleContent>
			</Bubble>
			<MessageFooter>Delivered</MessageFooter>
		</MessageContent>
	</Message>
	<Message>
		<MessageAvatar>
			<Avatar.Root>
				<Avatar.Image src="https://github.com/shadcn.png" alt="@rabbit" />
				<Avatar.Fallback>R</Avatar.Fallback>
			</Avatar.Root>
		</MessageAvatar>
		<MessageContent>
			<BubbleGroup>
				<Bubble variant="muted">
					<BubbleContent>It's always a one-line change 😭.</BubbleContent>
				</Bubble>
				<Bubble variant="muted">
					<BubbleContent>Alright, let me take a look.</BubbleContent>
					<BubbleReactions aria-label="Reactions: thumbs up">
						<span>👍</span>
					</BubbleReactions>
				</Bubble>
			</BubbleGroup>
		</MessageContent>
	</Message>
	<Marker role="status">
		<MarkerContent class="shimmer">
			<span class="font-medium">Oliver</span> is typing...
		</MarkerContent>
	</Marker>
</div>
