// apps/preview-vue/src/vue/message-group.vue
<script setup lang="ts">
import { Avatar, AvatarFallback, AvatarImage } from '@/ui/avatar'
import { Bubble, BubbleContent } from '@/ui/bubble'
import {
  Message,
  MessageAvatar,
  MessageContent,
  MessageGroup,
} from '@/ui/message'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-6 py-12">
    <MessageGroup>
      <Message>
        <MessageAvatar />
        <MessageContent>
          <Bubble variant="muted">
            <BubbleContent>I checked the registry addresses.</BubbleContent>
          </Bubble>
        </MessageContent>
      </Message>
      <Message>
        <MessageAvatar>
          <Avatar>
            <AvatarImage src="https://images.unsplash.com/photo-1599566150163-29194dcaad36?w=96&auto=format&fit=crop" alt="@avatar" />
            <AvatarFallback>CN</AvatarFallback>
          </Avatar>
        </MessageAvatar>
        <MessageContent>
          <Bubble variant="muted">
            <BubbleContent>
              The component and example JSON now live under the UI registry.
            </BubbleContent>
          </Bubble>
        </MessageContent>
      </Message>
    </MessageGroup>
  </div>
</template>

// apps/preview-svelte/src/svelte/message-group.svelte
<script lang="ts">
	import * as Avatar from "@/svelte-ui/avatar/index.js";
	import { Bubble, BubbleContent } from "@/svelte-ui/bubble/index.js";
	import {
		Message,
		MessageAvatar,
		MessageContent,
		MessageGroup,
	} from "@/svelte-ui/message/index.js";
</script>

<div class="flex w-full max-w-sm flex-col gap-6 py-12">
	<MessageGroup>
		<Message>
			<MessageAvatar />
			<MessageContent>
				<Bubble variant="muted">
					<BubbleContent>I checked the registry addresses.</BubbleContent>
				</Bubble>
			</MessageContent>
		</Message>
		<Message>
			<MessageAvatar>
				<Avatar.Root>
					<Avatar.Image src="https://github.com/shadcn.png" alt="@avatar" />
					<Avatar.Fallback>CN</Avatar.Fallback>
				</Avatar.Root>
			</MessageAvatar>
			<MessageContent>
				<Bubble variant="muted">
					<BubbleContent>
						The component and example JSON now live under the UI registry.
					</BubbleContent>
				</Bubble>
			</MessageContent>
		</Message>
	</MessageGroup>
</div>
