// packages/registry-vue/ui/button/Button.vue
<script setup lang="ts">
import type { PrimitiveProps } from "reka-ui"
import type { HTMLAttributes } from "vue"
import type { ButtonVariants } from "."
import { computed } from "vue"
import { Primitive } from "reka-ui"
import { cn } from "@/lib/utils"
import IconPlaceholder from "@/components/icon-placeholder/IconPlaceholder.vue"
import { buttonVariants } from "."

interface Props extends PrimitiveProps {
  variant?: ButtonVariants["variant"]
  size?: ButtonVariants["size"]
  class?: HTMLAttributes["class"]
  /** [FORCE-UI] shows a spinner and blocks interaction, for async actions — mirrors the Figma `State=Loading` variant */
  loading?: boolean
  disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  as: "button",
  loading: false,
})

// [FORCE-UI] loading buttons are inert while the async action runs
const disabled = computed(() => props.disabled || props.loading || undefined)
</script>

<template>
  <Primitive
    data-slot="button"
    :data-variant="variant"
    :data-size="size"
    :data-loading="props.loading ? '' : undefined"
    :aria-busy="props.loading || undefined"
    :disabled="disabled"
    :as="as"
    :as-child="asChild"
    :class="cn(buttonVariants({ variant, size }), props.class)"
  >
    <span v-if="props.loading" data-slot="button-spinner" aria-hidden="true" class="inline-flex animate-spin">
      <IconPlaceholder
        lucide="Loader2Icon"
        materialSymbols="progress_activity"
        tabler="IconLoader"
        hugeicons="Loading03Icon"
        phosphor="SpinnerIcon"
        remixicon="RiLoaderLine"
      />
    </span>
    <slot />
  </Primitive>
</template>

// packages/registry-svelte/ui/button/button.svelte
<script lang="ts" module>
	import { cn, type WithElementRef } from "$lib/utils.js";
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from "svelte/elements";
	import { type VariantProps, tv } from "tailwind-variants";

	export const buttonVariants = tv({
		base: "cn-button group/button inline-flex shrink-0 items-center justify-center whitespace-nowrap transition-all outline-none select-none disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
		variants: {
			variant: {
				default: "cn-button-variant-default",
				outline: "cn-button-variant-outline",
				secondary: "cn-button-variant-secondary",
				ghost: "cn-button-variant-ghost",
				destructive: "cn-button-variant-destructive",
				link: "cn-button-variant-link",
			},
			size: {
				default: "cn-button-size-default",
				xs: "cn-button-size-xs",
				sm: "cn-button-size-sm",
				lg: "cn-button-size-lg",
				icon: "cn-button-size-icon",
				"icon-xs": "cn-button-size-icon-xs",
				"icon-sm": "cn-button-size-icon-sm",
				"icon-lg": "cn-button-size-icon-lg",
			},
		},
		defaultVariants: {
			variant: "default",
			size: "default",
		},
	});

	export type ButtonVariant = VariantProps<typeof buttonVariants>["variant"];
	export type ButtonSize = VariantProps<typeof buttonVariants>["size"];

	export type ButtonProps = WithElementRef<HTMLButtonAttributes> &
		WithElementRef<HTMLAnchorAttributes> & {
			variant?: ButtonVariant;
			size?: ButtonSize;
			/** [FORCE-UI] shows a spinner and blocks interaction, for async actions — mirrors the Figma `State=Loading` variant */
			loading?: boolean;
		};
</script>

<script lang="ts">
	import IconPlaceholder from "$lib/components/icon-placeholder/icon-placeholder.svelte";

	let {
		class: className,
		variant = "default",
		size = "default",
		ref = $bindable(null),
		href = undefined,
		type = "button",
		disabled,
		loading = false,
		children,
		...restProps
	}: ButtonProps = $props();
</script>

{#if href}
	<a
		bind:this={ref}
		data-slot="button"
		data-loading={loading ? "" : undefined}
		aria-busy={loading || undefined}
		class={cn(buttonVariants({ variant, size }), className)}
		href={disabled || loading ? undefined : href}
		aria-disabled={disabled || loading}
		role={disabled || loading ? "link" : undefined}
		tabindex={disabled || loading ? -1 : undefined}
		{...restProps}
	>
		{#if loading}
			<span data-slot="button-spinner" aria-hidden="true" class="inline-flex animate-spin">
				<IconPlaceholder
					lucide="Loader2Icon"
					materialSymbols="progress_activity"
					tabler="IconLoader"
					hugeicons="Loading03Icon"
					phosphor="SpinnerIcon"
					remixicon="RiLoaderLine"
				/>
			</span>
		{/if}
		{@render children?.()}
	</a>
{:else}
	<button
		bind:this={ref}
		data-slot="button"
		data-loading={loading ? "" : undefined}
		aria-busy={loading || undefined}
		class={cn(buttonVariants({ variant, size }), className)}
		{type}
		disabled={disabled || loading}
		{...restProps}
	>
		{#if loading}
			<span data-slot="button-spinner" aria-hidden="true" class="inline-flex animate-spin">
				<IconPlaceholder
					lucide="Loader2Icon"
					materialSymbols="progress_activity"
					tabler="IconLoader"
					hugeicons="Loading03Icon"
					phosphor="SpinnerIcon"
					remixicon="RiLoaderLine"
				/>
			</span>
		{/if}
		{@render children?.()}
	</button>
{/if}
