// packages/registry-vue/ui/message/MessageFooter.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="message-footer"
    :class="
      cn(
        'cn-message-footer flex max-w-full min-w-0 items-center group-data-[align=end]/message:justify-end',
        props.class,
      )
    "
  >
    <slot />
  </div>
</template>

// packages/registry-svelte/ui/message/message-footer.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> = $props();
</script>

<div
	bind:this={ref}
	data-slot="message-footer"
	class={cn(
		"cn-message-footer flex max-w-full min-w-0 items-center group-data-[align=end]/message:justify-end",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>
