// packages/registry-vue/ui/message/Message.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = withDefaults(
  defineProps<{
    align?: "start" | "end"
    class?: HTMLAttributes["class"]
  }>(),
  {
    align: "start",
  },
)
</script>

<template>
  <div
    data-slot="message"
    :data-align="props.align"
    :class="
      cn(
        'cn-message group/message relative flex w-full min-w-0 data-[align=end]:flex-row-reverse',
        props.class,
      )
    "
  >
    <slot />
  </div>
</template>

// packages/registry-svelte/ui/message/message.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		align = "start",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		align?: "start" | "end";
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="message"
	data-align={align}
	class={cn(
		"cn-message group/message relative flex w-full min-w-0 data-[align=end]:flex-row-reverse",
		className
	)}
	{...restProps}
>
	{@render children?.()}
</div>
