// apps/preview-vue/src/vue/bubble-collapsible.vue
<script setup lang="ts">
import { ref } from "vue"
import KeyboardArrowDownIcon from "@material-symbols/svg-400/rounded/keyboard_arrow_down.svg?component"
import { Bubble, BubbleContent } from '@/ui/bubble'
import { Button } from '@/ui/button'
import { Collapsible, CollapsibleTrigger } from '@/ui/collapsible'

const text = `The accessibility review found two focus states that were visually too subtle in dark mode.

I checked the dialog, menu, and drawer paths because each one renders focusable controls inside a layered surface.

The dialog and drawer are fine. The menu needs the hover and focus tokens split so keyboard focus stays visible when the pointer is not involved.

I also recommend keeping the change in the style file instead of the primitive so the other themes can choose their own focus treatment later.`

const previewLength = 180
const open = ref(false)
const isLong = text.length > previewLength
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Bubble variant="muted">
      <BubbleContent>How can I help you today?</BubbleContent>
    </Bubble>

    <Bubble variant="muted" align="end">
      <BubbleContent class="whitespace-pre-line">
        <Collapsible v-model:open="open">
          <div>{{ open || !isLong ? text : `${text.slice(0, previewLength)}...` }}</div>
          <CollapsibleTrigger v-if="isLong" as-child>
            <Button
              variant="link"
              class="gap-1 p-0 text-muted-foreground"
            >
              {{ open ? "Show less" : "Show more" }}
              <KeyboardArrowDownIcon
                data-icon="inline-end"
                class="group-data-panel-open/button:rotate-180"
              />
            </Button>
          </CollapsibleTrigger>
        </Collapsible>
      </BubbleContent>
    </Bubble>
  </div>
</template>

// apps/preview-angular/src/angular/bubble-collapsible.ts
import { Bubble, BubbleContent } from "@/angular-ui/bubble"
import { Button } from "@/angular-ui/button"
import { Collapsible, CollapsibleTrigger } from "@/angular-ui/collapsible"
import { Component, signal } from "@angular/core"

// apps/v4/examples/base/bubble-collapsible.tsx — React useState → Angular signal.
const TEXT = `The accessibility review found two focus states that were visually too subtle in dark mode.

I checked the dialog, menu, and drawer paths because each one renders focusable controls inside a layered surface.

The dialog and drawer are fine. The menu needs the hover and focus tokens split so keyboard focus stays visible when the pointer is not involved.

I also recommend keeping the change in the style file instead of the primitive so the other themes can choose their own focus treatment later.`

const PREVIEW_LENGTH = 180

@Component({
  selector: "preview-bubble-collapsible",
  standalone: true,
  imports: [Bubble, BubbleContent, Button, Collapsible, CollapsibleTrigger],
  template: `
    <div class="flex w-full max-w-sm flex-col gap-8 py-12">
      <div uiBubble variant="muted"><div uiBubbleContent>How can I help you today?</div></div>
      <div uiBubble variant="muted" align="end">
        <div uiBubbleContent class="whitespace-pre-line">
          <div uiCollapsible>
            <div>{{ open() || !isLong ? text : preview }}</div>
            @if (isLong) {
              <button uiButton variant="link" class="gap-1 p-0 text-muted-foreground" uiCollapsibleTrigger type="button">
                {{ open() ? 'Show less' : 'Show more' }}
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -960 960 960" data-icon="inline-end" class="size-4 group-data-panel-open/uiCollapsible:rotate-180" aria-hidden="true"><path d="M480-344 240-584l56-56 184 184 184-184 56 56-240 240Z"/></svg>
              </button>
            }
          </div>
        </div>
      </div>
    </div>
  `,
})
export class BubbleCollapsibleComponent {
  protected readonly text = TEXT
  protected readonly isLong = TEXT.length > PREVIEW_LENGTH
  protected readonly preview = `${TEXT.slice(0, PREVIEW_LENGTH)}...`
  protected readonly open = signal(false)
}

export default BubbleCollapsibleComponent
