// apps/preview-vue/src/vue/drawer-dialog.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/ui/dialog"
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/ui/drawer"
import { Input } from "@/ui/input"
import { Label } from "@/ui/label"
import { useMediaQuery } from "@vueuse/core"
import { ref } from "vue"

const isDesktop = useMediaQuery("(min-width: 768px)")
const open = ref(false)
</script>

<template>
  <Dialog v-if="isDesktop" v-model:open="open">
    <DialogTrigger as-child>
      <Button variant="outline"> Edit Profile </Button>
    </DialogTrigger>
    <DialogContent class="sm:max-w-[425px]">
      <DialogHeader>
        <DialogTitle>Edit profile</DialogTitle>
        <DialogDescription>
          Make changes to your profile here. Click save when you're done.
        </DialogDescription>
      </DialogHeader>
      <form class="grid items-start gap-6">
        <div class="grid gap-3">
          <Label for="email">Email</Label>
          <Input type="email" id="email" default-value="shadcn@example.com" />
        </div>
        <div class="grid gap-3">
          <Label for="username">Username</Label>
          <Input id="username" default-value="@shadcn" />
        </div>
        <Button type="submit"> Save changes </Button>
      </form>
    </DialogContent>
  </Dialog>

  <Drawer v-else v-model:open="open">
    <DrawerTrigger as-child>
      <Button variant="outline"> Edit Profile </Button>
    </DrawerTrigger>
    <DrawerContent>
      <DrawerHeader class="text-left">
        <DrawerTitle>Edit profile</DrawerTitle>
        <DrawerDescription>
          Make changes to your profile here. Click save when you're done.
        </DrawerDescription>
      </DrawerHeader>
      <form class="grid items-start gap-6 px-4">
        <div class="grid gap-3">
          <Label for="email-drawer">Email</Label>
          <Input
            type="email"
            id="email-drawer"
            default-value="shadcn@example.com"
          />
        </div>
        <div class="grid gap-3">
          <Label for="username-drawer">Username</Label>
          <Input id="username-drawer" default-value="@shadcn" />
        </div>
        <Button type="submit"> Save changes </Button>
      </form>
      <DrawerFooter class="pt-2">
        <DrawerClose as-child>
          <Button variant="outline"> Cancel </Button>
        </DrawerClose>
      </DrawerFooter>
    </DrawerContent>
  </Drawer>
</template>

// apps/preview-angular/src/angular/drawer-dialog.ts
import { Component, signal } from "@angular/core"

import { Button } from "@/angular-ui/button"
import {
  DrawerContent,
  DrawerDescription,
  DrawerHeader,
  DrawerOverlay,
  DrawerPortal,
  DrawerRoot,
  DrawerTitle,
  DrawerTrigger,
} from "@/angular-ui/drawer"
import { Input } from "@/angular-ui/input"
import { Label } from "@/angular-ui/label"

// apps/v4/examples/base/drawer-dialog.tsx — responsive dialog pattern: the
// React version renders a Dialog on desktop (md+) and this Drawer on mobile.
// The angular dialog port is pending, so the preview shows the drawer half;
// the Callout on the docs page documents the deviation.
@Component({
  selector: "preview-drawer-dialog",
  standalone: true,
  imports: [
    DrawerRoot,
    DrawerTrigger,
    DrawerPortal,
    DrawerOverlay,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    Button,
    Input,
    Label,
  ],
  template: `<div uiDrawerRoot [(open)]="open">
  <button uiButton variant="outline" uiDrawerTrigger>Edit Profile</button>
  <ng-template uiDrawerPortal>
    <div uiDrawerOverlay></div>
    <div uiDrawerContent direction="bottom">
      <div uiDrawerHeader class="text-left">
        <h2 uiDrawerTitle>Edit profile</h2>
        <p uiDrawerDescription>Make changes to your profile here. Click save when you're done.</p>
      </div>
      <form class="grid items-start gap-6 p-4" (submit)="submit($event)">
        <div class="grid gap-3">
          <label uiLabel for="drawer-dialog-email">Email</label>
          <input uiInput type="email" id="drawer-dialog-email" value="shadcn@example.com" />
        </div>
        <div class="grid gap-3">
          <label uiLabel for="drawer-dialog-username">Username</label>
          <input uiInput id="drawer-dialog-username" value="@shadcn" />
        </div>
        <button uiButton type="submit">Save changes</button>
      </form>
    </div>
  </ng-template>
</div>`,
})
export class DrawerDialogComponent {
  protected readonly open = signal(false)

  protected submit(event: Event): void {
    event.preventDefault()
    this.open.set(false)
  }
}

export default DrawerDialogComponent
