// apps/preview-vue/src/vue/drawer-non-modal.vue
<script setup lang="ts">
import { Button } from "@/ui/button"
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from "@/ui/drawer"
import { ref } from "vue"

const open = ref(false)
</script>

<template>
  <div class="flex flex-col items-start gap-4">
    <p class="text-sm text-muted-foreground">
      While this drawer is open you can still interact with the page — it is
      non-modal.
    </p>
    <Drawer v-model:open="open" :modal="false">
      <DrawerTrigger as-child>
        <Button variant="outline">Open non-modal drawer</Button>
      </DrawerTrigger>
      <DrawerContent>
        <DrawerHeader>
          <DrawerTitle>Non-modal drawer</DrawerTitle>
          <DrawerDescription
            >No overlay; the rest of the page stays
            interactive.</DrawerDescription
          >
        </DrawerHeader>
        <DrawerFooter>
          <DrawerClose as-child>
            <Button variant="outline">Close</Button>
          </DrawerClose>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  </div>
</template>

// apps/preview-angular/src/angular/drawer-non-modal.ts
import { Component } from "@angular/core"

import { Button } from "@/angular-ui/button"
import {
  DrawerClose,
  DrawerContent,
  DrawerFooter,
  DrawerHeader,
  DrawerOverlay,
  DrawerPortal,
  DrawerRoot,
  DrawerTitle,
  DrawerTrigger,
} from "@/angular-ui/drawer"

// apps/v4/examples/base/drawer-non-modal.tsx — modal={false} +
// disablePointerDismissal, so the page stays interactive while open.
@Component({
  selector: "preview-drawer-non-modal",
  standalone: true,
  imports: [
    DrawerRoot,
    DrawerTrigger,
    DrawerPortal,
    DrawerOverlay,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerFooter,
    DrawerClose,
    Button,
  ],
  template: `<div uiDrawerRoot [modal]="false" [disablePointerDismissal]="true">
  <button uiButton variant="outline" uiDrawerTrigger>Non Modal</button>
  <ng-template uiDrawerPortal>
    <div uiDrawerOverlay></div>
    <div uiDrawerContent direction="bottom">
      <div uiDrawerHeader>
        <h2 uiDrawerTitle>Non Modal Drawer</h2>
      </div>
      <div class="flex-1 p-4">
        <div class="h-80 w-full rounded-2xl bg-muted"></div>
      </div>
      <div uiDrawerFooter>
        <button uiButton uiDrawerClose>Close</button>
      </div>
    </div>
  </ng-template>
</div>`,
})
export class DrawerNonModalComponent {}

export default DrawerNonModalComponent
