// apps/preview-vue/src/vue/marker-variants.vue
<script setup lang="ts">
import {
  Marker,
  MarkerContent,
} from '@/ui/marker'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Marker>
      <MarkerContent>A default marker for inline notes.</MarkerContent>
    </Marker>
    <Marker variant="separator">
      <MarkerContent>A separator marker</MarkerContent>
    </Marker>
    <Marker variant="border">
      <MarkerContent>A border marker for row boundaries.</MarkerContent>
    </Marker>
  </div>
</template>

// apps/preview-angular/src/angular/marker-variants.ts
import { Marker, MarkerContent, MarkerIcon } from "@/angular-ui/marker"
import { Component } from "@angular/core"
@Component({
  selector: "preview-marker-variants",
  standalone: true,
  imports: [Marker, MarkerContent, MarkerIcon],
  template: `
    <div class="flex w-full flex-col gap-8 py-12 sm:max-w-sm">
      <div uiMarker>
        <span uiMarkerContent>A default marker for inline notes.</span>
      </div>
      <div uiMarker variant="separator">
        <span uiMarkerContent>A separator marker</span>
      </div>
      <div uiMarker variant="border">
        <span uiMarkerContent>A border marker for row boundaries.</span>
      </div>
    </div>
  `
})
export class MarkerVariantsComponent {}{}

export default MarkerVariantsComponent
