// apps/preview-vue/src/vue/message-scroller-group-chat.vue
<script setup lang="ts">
import { Bubble, BubbleContent } from "@/ui/bubble"
import { Button } from "@/ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/ui/card"
import {
  MessageScroller,
  MessageScrollerButton,
  MessageScrollerContent,
  MessageScrollerItem,
  MessageScrollerProvider,
  MessageScrollerViewport,
} from "@/ui/message-scroller"
import RotateCwIcon from "@material-symbols/svg-400/rounded/refresh.svg?component"
import { ref } from "vue"

interface Turn {
  id: number
  sender: string
  role: "me" | "them"
  text: string
}

let nextId = 0
function turn(sender: string, role: Turn["role"], text: string): Turn {
  return { id: nextId++, sender, role, text }
}

const initial: Turn[] = [
  turn(
    "Grace",
    "them",
    "@mary, the astrophage line keeps matching Venus energy output. Can you check my math?"
  ),
  turn(
    "Mary (Agent)",
    "them",
    "Checked — your exponent is off by one. The curve should be E ∝ L² not E ∝ L."
  ),
  turn("Grace", "them", "Fixed it. The residual drops to 0.3%."),
  turn("You", "me", "Nice. Pushing to the shared notebook now."),
]

const messages = ref([...initial])
const draft = ref("")

function send() {
  const text = draft.value.trim()
  if (!text) return
  messages.value.push(turn("You", "me", text))
  draft.value = ""
}
</script>

<template>
  <Card class="mx-auto flex h-[28rem] w-full max-w-sm flex-col gap-0">
    <CardHeader class="border-b">
      <CardTitle>Project Hail Mary</CardTitle>
      <CardDescription>Group chat turns with agent mentions.</CardDescription>
      <CardAction>
        <Button
          variant="outline"
          size="icon"
          aria-label="Reset chat"
          @click="messages = [...initial]"
        >
          <RotateCwIcon />
        </Button>
      </CardAction>
    </CardHeader>
    <CardContent class="min-h-0 flex-1 overflow-hidden p-0">
      <MessageScrollerProvider auto-scroll>
        <MessageScroller class="h-full">
          <MessageScrollerViewport>
            <MessageScrollerContent class="gap-3 p-4">
              <MessageScrollerItem
                v-for="m in messages"
                :key="m.id"
                :scroll-anchor="m.role === 'me'"
              >
                <p class="mb-1 text-xs font-medium text-muted-foreground">
                  {{ m.sender }}
                </p>
                <Bubble
                  :align="m.role === 'me' ? 'end' : 'start'"
                  :variant="m.role === 'me' ? 'tinted' : 'outline'"
                >
                  <BubbleContent>
                    <p class="text-sm">{{ m.text }}</p>
                  </BubbleContent>
                </Bubble>
              </MessageScrollerItem>
            </MessageScrollerContent>
          </MessageScrollerViewport>
          <MessageScrollerButton />
        </MessageScroller>
      </MessageScrollerProvider>
    </CardContent>
    <form class="flex gap-2 border-t p-4" @submit.prevent="send">
      <input
        v-model="draft"
        placeholder="Reply to the group…"
        class="w-full rounded-md border bg-transparent px-3 py-1 text-sm outline-none"
      />
      <Button type="submit" size="sm">Send</Button>
    </form>
  </Card>
</template>

// apps/preview-angular/src/angular/message-scroller-group-chat.ts
import { Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/angular-ui/card"
import {
  MessageScroller,
  MessageScrollerButton,
  MessageScrollerContent,
  MessageScrollerItem,
  MessageScrollerProvider,
  MessageScrollerViewport,
} from "@/angular-ui/message-scroller"
import { Message, MessageContent, MessageHeader } from "@/angular-ui/message"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/angular-ui/tooltip"
import { Component, signal } from "@angular/core"

// apps/v4/examples/base/message-scroller-group-chat.tsx
type GroupChatItem =
  | { id: string; type: "event"; text: string; scrollAnchor?: boolean }
  | { id: string; type: "message"; sender: string; role: "assistant" | "participant"; text: string; scrollAnchor?: boolean }

const currentUser = "Grace"

const initialItems: GroupChatItem[] = [
  { id: "group-1", type: "message", sender: "Grace", role: "participant", text: "@mary, the astrophage line keeps matching Venus energy output. Can you check my math?" },
  { id: "group-2", type: "message", sender: "Mary (Agent)", role: "assistant", text: "Yes. Confirmed. The curve points to a microorganism harvesting stellar energy and breeding near carbon dioxide. If @rocky agrees, this is the clue we need." },
  { id: "group-3", type: "message", sender: "Grace", role: "participant", text: "ping @rocky", scrollAnchor: true },
]
const rockyMarker: GroupChatItem = { id: "group-4", type: "event", text: "Rocky has joined the chat", scrollAnchor: true }
const rockyMessage: GroupChatItem = { id: "group-5", type: "message", sender: "Rocky", role: "participant", text: "Amaze. Astrophage eats light, makes heat, goes to carbon dioxide. Rocky has fuel model. Grace is smart." }

@Component({
  selector: "preview-message-scroller-group-chat",
  standalone: true,
  imports: [Card, CardAction, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, MessageScrollerProvider, MessageScroller, MessageScrollerViewport, MessageScrollerContent, MessageScrollerItem, MessageScrollerButton, Message, MessageContent, MessageHeader, Tooltip, TooltipContent, TooltipTrigger],
  template: `
    <div uiMessageScrollerProvider>
      <div class="relative flex flex-col gap-4">
        <div uiCard class="mx-auto h-140 w-full max-w-sm gap-0">
          <div uiCardHeader class="gap-1 border-b">
            <div uiCardTitle>Group Chat</div>
            <div uiCardDescription>Events and messages share one transcript.</div>
          </div>
          <div uiCardContent class="flex-1 overflow-hidden p-0">
            <div uiMessageScroller>
              <div uiMessageScrollerViewport ariaLabel="Group transcript">
                <div uiMessageScrollerContent class="p-(--card-spacing)">
                  @for (item of items(); track item.id) {
                    @if (item.type === "event") {
                      <div uiMessageScrollerItem [scrollAnchor]="item.scrollAnchor ?? false" class="my-2 text-center text-xs text-muted-foreground">
                        {{ item.text }}
                      </div>
                    } @else {
                      <div uiMessageScrollerItem [scrollAnchor]="item.scrollAnchor ?? false">
                        <div uiMessage [align]="item.sender === currentUser ? 'end' : 'start'">
                          @if (item.sender !== previousSender($index)) {
                            <div uiMessageHeader>{{ item.sender }}</div>
                          }
                          <div uiMessageContent>
                            <span class="whitespace-pre-wrap">{{ item.text }}</span>
                          </div>
                        </div>
                      </div>
                    }
                  }
                </div>
              </div>
              <button uiMessageScrollerButton></button>
            </div>
          </div>
          <div uiCardFooter>
            <div uiTooltip>
              <button uiTooltipTrigger uiButton variant="outline" size="sm" (click)="joinRocky()">Add Rocky</button>
              <div uiTooltipContent><p>Appends the join event and Rocky's reply</p></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
})
export class MessageScrollerGroupChatComponent {
  protected readonly currentUser = currentUser
  protected readonly items = signal<GroupChatItem[]>([...initialItems])

  protected previousSender(index: number): string | undefined {
    const list = this.items()
    for (let i = index - 1; i >= 0; i--) {
      const prior = list[i]
      if (prior.type === "message") return prior.sender
    }
    return undefined
  }

  protected joinRocky(): void {
    this.items.update((list) =>
      list.some((i) => i.id === rockyMessage.id) ? list : [...list, rockyMarker, rockyMessage]
    )
  }
}

export default MessageScrollerGroupChatComponent
