// apps/preview-svelte/src/svelte/sheet-rtl.svelte
<script lang="ts">
	import { Button, buttonVariants } from "@/svelte-ui/button/index.js";
	import * as Sheet from "@/svelte-ui/sheet/index.js";
	import { Input } from "@/svelte-ui/input/index.js";
	import { Label } from "@/svelte-ui/label/index.js";
</script>

<Sheet.Root>
	<Sheet.Trigger class={buttonVariants({ variant: "outline" })}>فتح</Sheet.Trigger>
	<Sheet.Content dir="rtl" side="left">
		<Sheet.Header>
			<Sheet.Title>تعديل الملف الشخصي</Sheet.Title>
			<Sheet.Description>
				قم بإجراء تغييرات على ملفك الشخصي هنا. انقر حفظ عند الانتهاء.
			</Sheet.Description>
		</Sheet.Header>
		<div class="grid flex-1 auto-rows-min gap-6 px-4">
			<div class="grid gap-3">
				<Label for="sheet-rtl-name">الاسم</Label>
				<Input id="sheet-rtl-name" value="Pedro Duarte" />
			</div>
			<div class="grid gap-3">
				<Label for="sheet-rtl-username">اسم المستخدم</Label>
				<Input id="sheet-rtl-username" value="@peduarte" />
			</div>
		</div>
		<Sheet.Footer>
			<Button type="submit">حفظ التغييرات</Button>
			<Sheet.Close class={buttonVariants({ variant: "outline" })}>إغلاق</Sheet.Close>
		</Sheet.Footer>
	</Sheet.Content>
</Sheet.Root>

// apps/preview-angular/src/angular/sheet-rtl.ts
import { Component } from "@angular/core"

import { Button } from "@/angular-ui/button"
import { Field, FieldGroup, FieldLabel } from "@/angular-ui/field"
import { Input } from "@/angular-ui/input"
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/angular-ui/sheet"

// apps/v4/examples/base/sheet-rtl.tsx — the React example drives dir/labels
// from the language-selector translations (ar). Static Arabic labels + dir="rtl"
// + side="left" render the same visual state.
@Component({
  selector: "preview-sheet-rtl",
  standalone: true,
  imports: [
    Sheet,
    SheetTrigger,
    SheetContent,
    SheetHeader,
    SheetFooter,
    SheetTitle,
    SheetDescription,
    SheetClose,
    Button,
    Field,
    FieldGroup,
    FieldLabel,
    Input,
  ],
  template: `
    <div uiSheet>
      <button uiButton variant="outline" uiSheetTrigger>فتح</button>
      <ng-template uiSheetPortal>
        <div uiSheetOverlay></div>
        <div uiSheetContent dir="rtl" side="left">
          <div uiSheetHeader>
            <h2 uiSheetTitle>تعديل الملف الشخصي</h2>
            <p uiSheetDescription>قم بإجراء تغييرات على ملفك الشخصي هنا. انقر حفظ عند الانتهاء.</p>
          </div>
          <div uiFieldGroup class="px-4">
            <div uiField>
              <label uiFieldLabel for="sheet-rtl-name">الاسم</label>
              <input uiInput id="sheet-rtl-name" value="Pedro Duarte" />
            </div>
            <div uiField>
              <label uiFieldLabel for="sheet-rtl-username">اسم المستخدم</label>
              <input uiInput id="sheet-rtl-username" value="peduarte" />
            </div>
          </div>
          <div uiSheetFooter>
            <button uiButton type="submit">حفظ التغييرات</button>
            <button uiButton variant="outline" uiSheetClose>إغلاق</button>
          </div>
        </div>
      </ng-template>
    </div>
  `,
})
export class SheetRtlComponent {}

export default SheetRtlComponent
