// apps/preview-svelte/src/svelte/marker-separator.svelte
<script lang="ts">
	import { Marker, MarkerContent } from "@/svelte-ui/marker/index.js";
</script>

<div class="flex w-full max-w-sm flex-col gap-8 py-12">
	<Marker variant="separator">
		<MarkerContent>Today</MarkerContent>
	</Marker>
	<Marker variant="separator">
		<MarkerContent>Worked for 42s</MarkerContent>
	</Marker>
	<Marker variant="separator">
		<MarkerContent>Conversation compacted</MarkerContent>
	</Marker>
</div>

// packages/registry-vue/examples/marker/MarkerSeparator.vue
<script setup lang="ts">
import {
  Marker,
  MarkerContent,
} from '@/ui/marker'
</script>

<template>
  <div class="flex w-full max-w-sm flex-col gap-8 py-12">
    <Marker variant="separator">
      <MarkerContent>Today</MarkerContent>
    </Marker>
    <Marker variant="separator">
      <MarkerContent>Worked for 42s</MarkerContent>
    </Marker>
    <Marker variant="separator">
      <MarkerContent>Conversation compacted</MarkerContent>
    </Marker>
  </div>
</template>
