// packages/registry-vue/blocks/sidebar-10/AppSidebar.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-10
import { h } from 'vue'
import type { Component } from 'vue'
import TeamSwitcher from './TeamSwitcher.vue'
import NavMain from './NavMain.vue'
import NavFavorites from './NavFavorites.vue'
import NavWorkspaces from './NavWorkspaces.vue'
import NavSecondary from './NavSecondary.vue'
import Search from '@material-symbols/svg-400/rounded/search.svg?component'
import Stars from '@material-symbols/svg-400/rounded/stars.svg?component'
import Home from '@material-symbols/svg-400/rounded/home.svg?component'
import Inbox from '@material-symbols/svg-400/rounded/inbox.svg?component'
import CalendarMonth from '@material-symbols/svg-400/rounded/calendar_month.svg?component'
import Tune from '@material-symbols/svg-400/rounded/tune.svg?component'
import ViewQuilt from '@material-symbols/svg-400/rounded/view_quilt.svg?component'
import Delete from '@material-symbols/svg-400/rounded/delete.svg?component'
import HelpCenter from '@material-symbols/svg-400/rounded/help_center.svg?component'
import {
  Sidebar,
  SidebarContent,
  SidebarHeader,
  SidebarRail,
} from '@/ui/sidebar'

// Lucide command icon as a functional component.
const Command = () =>
  h('svg', { xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', 'stroke-width': '2', 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }, [
    h('path', { d: 'M15 6v12a3 3 0 1 0 3-3H6a3 3 0 1 0 3 3V6a3 3 0 1 0-3 3h12a3 3 0 1 0-3-3' }),
  ])

// This is sample data.
const data = {
  teams: [
    { name: 'Acme Inc', logo: Command, plan: 'Enterprise' },
    { name: 'Acme Corp.', logo: Command, plan: 'Startup' },
    { name: 'Evil Corp.', logo: Command, plan: 'Free' },
  ],
  navMain: [
    { title: 'Search', url: '#', icon: Search as Component },
    { title: 'Ask AI', url: '#', icon: Stars as Component },
    { title: 'Home', url: '#', icon: Home as Component, isActive: true },
    { title: 'Inbox', url: '#', icon: Inbox as Component, badge: '10' },
  ],
  navSecondary: [
    { title: 'Calendar', url: '#', icon: CalendarMonth as Component },
    { title: 'Settings', url: '#', icon: Tune as Component },
    { title: 'Templates', url: '#', icon: ViewQuilt as Component },
    { title: 'Trash', url: '#', icon: Delete as Component },
    { title: 'Help', url: '#', icon: HelpCenter as Component },
  ],
  favorites: [
    { name: 'Project Management & Task Tracking', url: '#', emoji: '📊' },
    { name: 'Family Recipe Collection & Meal Planning', url: '#', emoji: '🍳' },
    { name: 'Fitness Tracker & Workout Routines', url: '#', emoji: '💪' },
    { name: 'Book Notes & Reading List', url: '#', emoji: '📚' },
    { name: 'Sustainable Gardening Tips & Plant Care', url: '#', emoji: '🌱' },
    { name: 'Language Learning Progress & Resources', url: '#', emoji: '🗣️' },
    { name: 'Home Renovation Ideas & Budget Tracker', url: '#', emoji: '🏠' },
    { name: 'Personal Finance & Investment Portfolio', url: '#', emoji: '💰' },
    { name: 'Movie & TV Show Watchlist with Reviews', url: '#', emoji: '🎬' },
  ],
  workspaces: [
    {
      name: 'Personal Life Management',
      emoji: '🏠',
      pages: [
        { name: 'Daily Journal & Reflection', url: '#', emoji: '📔' },
        { name: 'Health & Wellness Tracker', url: '#', emoji: '🍏' },
        { name: 'Personal Growth & Learning Goals', url: '#', emoji: '🌟' },
      ],
    },
    {
      name: 'Professional Development',
      emoji: '💼',
      pages: [
        { name: 'Career Objectives & Milestones', url: '#', emoji: '🎯' },
        { name: 'Skill Acquisition & Training Log', url: '#', emoji: '🧠' },
        { name: 'Networking Contacts & Events', url: '#', emoji: '🤝' },
      ],
    },
  ],
}
</script>

<template>
  <Sidebar class="border-r-0">
    <SidebarHeader>
      <TeamSwitcher :teams="data.teams" />
      <NavMain :items="data.navMain" />
    </SidebarHeader>
    <SidebarContent>
      <NavFavorites :favorites="data.favorites" />
      <NavWorkspaces :workspaces="data.workspaces" />
      <NavSecondary :items="data.navSecondary" class="mt-auto" />
    </SidebarContent>
    <SidebarRail />
  </Sidebar>
</template>

// packages/registry-svelte/blocks/sidebar-10/components/app-sidebar.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-10 -->
<script lang="ts">
  import AudioLines from "~icons/ms/graphic_eq"
  import Send from "~icons/ms/send"
  import LifeBuoy from "~icons/ms/support"
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"

  import NavFavorites from "./nav-favorites.svelte"
  import NavMain from "./nav-main.svelte"
  import NavSecondary from "./nav-secondary.svelte"
  import NavWorkspaces from "./nav-workspaces.svelte"
  import TeamSwitcher from "./team-switcher.svelte"
</script>

<Sidebar.Root class="border-r-0">
  <Sidebar.Header>
    <TeamSwitcher
      teams={[
        { name: "Acme Inc", logo: AudioLines, plan: "Enterprise" },
        { name: "Acme Corp.", logo: Send, plan: "Startup" },
        { name: "Evil Corp.", logo: LifeBuoy, plan: "Free" },
      ]}
    />
    <NavMain
      items={[
        { title: "Search", url: "#", icon: Send, isActive: true },
        { title: "Ask AI", url: "#", icon: AudioLines },
        { title: "Settings", url: "#", icon: LifeBuoy },
      ]}
    />
  </Sidebar.Header>
  <Sidebar.Content>
    <NavFavorites
      favorites={[
        { name: "Project Management & Task Tracking", url: "#", emoji: "📊" },
        { name: "Team Meeting Notes", url: "#", emoji: "📝" },
        { name: "Resource Planning Overview", url: "#", emoji: "🗂️" },
      ]}
    />
    <NavWorkspaces
      workspaces={[
        {
          name: "Personal Workspace",
          emoji: "🏠",
          pages: [
            { name: "Code Editor Settings", emoji: "💻" },
            { name: "Reading List", emoji: "📚" },
          ],
        },
        {
          name: "Team Workspace",
          emoji: "👥",
          pages: [
            { name: "Design Review", emoji: "🎨" },
            { name: "Sprint Board", emoji: "🏃" },
          ],
        },
      ]}
    />
    <NavSecondary
      items={[
        { title: "Support", url: "#", icon: LifeBuoy },
        { title: "Feedback", url: "#", icon: Send },
      ]}
      class="mt-auto"
    />
  </Sidebar.Content>
  <Sidebar.Rail />
</Sidebar.Root>
