// packages/registry-vue/blocks/sidebar-10/NavMain.vue
<script setup lang="ts">
// [FORCE-UI] Vue port of registry/new-york-v4/blocks/sidebar-10
import type { Component } from 'vue'
import {
  SidebarMenu,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
} from '@/ui/sidebar'

const props = defineProps<{
  items: {
    title: string
    url: string
    icon: Component
    isActive?: boolean
    badge?: string
  }[]
}>()
</script>

<template>
  <SidebarMenu>
    <SidebarMenuItem v-for="item in props.items" :key="item.title">
      <SidebarMenuButton as-child :is-active="item.isActive">
        <a :href="item.url">
          <component :is="item.icon" />
          <span>{{ item.title }}</span>
        </a>
      </SidebarMenuButton>
      <SidebarMenuBadge v-if="item.badge">{{ item.badge }}</SidebarMenuBadge>
    </SidebarMenuItem>
  </SidebarMenu>
</template>

// packages/registry-svelte/blocks/sidebar-10/components/nav-main.svelte
<!-- [FORCE-UI] Ported from registry/new-york-v4/blocks/sidebar-10 -->
<script lang="ts">
  import * as Sidebar from "$lib/registry/ui/sidebar/index.js"
  import type { Component } from "svelte"

  let {
    items,
  }: {
    items: { title: string; url: string; icon: Component; isActive?: boolean }[]
  } = $props()
</script>

<Sidebar.Menu>
  {#each items as item (item.title)}
    <Sidebar.MenuItem>
      <Sidebar.MenuButton
        isActive={item.isActive ?? false}
        tooltipContent={item.title}
      >
        {#snippet child({ props })}
          <a href={item.url} {...props}>
            <item.icon />
            <span>{item.title}</span>
          </a>
        {/snippet}
      </Sidebar.MenuButton>
    </Sidebar.MenuItem>
  {/each}
</Sidebar.Menu>
