// packages/registry-vue/ui/bubble/Bubble.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import type { BubbleVariants, BubbleReactionsSide, BubbleReactionsAlign } from "."
import { cn } from "@/lib/utils"
import { bubbleVariants } from "."

const props = withDefaults(
  defineProps<{
    variant?: BubbleVariants["variant"]
    align?: "start" | "end"
    class?: HTMLAttributes["class"]
  }>(),
  {
    variant: "default",
    align: "start",
  },
)
</script>

<template>
  <div
    data-slot="bubble"
    :data-variant="props.variant"
    :data-align="props.align"
    :class="cn(bubbleVariants({ variant: props.variant }), props.class)"
  >
    <slot />
  </div>
</template>

// packages/registry-svelte/ui/bubble/bubble.svelte
<script lang="ts" module>
	import { type VariantProps, tv } from "tailwind-variants";

	export const bubbleVariants = tv({
		base: "cn-bubble group/bubble relative flex w-fit min-w-0 flex-col",
		variants: {
			variant: {
				default: "cn-bubble-variant-default",
				secondary: "cn-bubble-variant-secondary",
				muted: "cn-bubble-variant-muted",
				tinted: "cn-bubble-variant-tinted",
				outline: "cn-bubble-variant-outline",
				ghost: "cn-bubble-variant-ghost",
				destructive: "cn-bubble-variant-destructive",
			},
		},
		defaultVariants: {
			variant: "default",
		},
	});

	export type BubbleVariant = VariantProps<typeof bubbleVariants>["variant"];
</script>

<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { cn, type WithElementRef } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		variant = "default",
		align = "start",
		children,
		...restProps
	}: WithElementRef<HTMLAttributes<HTMLDivElement>> & {
		variant?: BubbleVariant;
		align?: "start" | "end";
	} = $props();
</script>

<div
	bind:this={ref}
	data-slot="bubble"
	data-variant={variant}
	data-align={align}
	class={cn(bubbleVariants({ variant }), className)}
	{...restProps}
>
	{@render children?.()}
</div>
